/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    I18nLanguageSnippet,
    I18nLanguageSnippetFromJSON,
    I18nLanguageSnippetToJSON,
    SupportedLanguage,
    SupportedLanguageFromJSON,
    SupportedLanguageToJSON,
} from '../models';

/**
 * no description
 */
export class LanguageApi extends runtime.BaseAPI {

    /**
     */
    async apiLanguageGoogleTranslateSupportedLanguagesGetRaw(): Promise<runtime.ApiResponse<Array<SupportedLanguage>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Language/GoogleTranslate-SupportedLanguages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SupportedLanguageFromJSON));
    }

    /**
     */
    async apiLanguageGoogleTranslateSupportedLanguagesGet(): Promise<Array<SupportedLanguage>> {
        const response = await this.apiLanguageGoogleTranslateSupportedLanguagesGetRaw();
        return await response.value();
    }

    /**
     */
    async apiLanguageYouTubeI18nLanguagesGetRaw(): Promise<runtime.ApiResponse<Array<I18nLanguageSnippet>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Language/YouTube-I18nLanguages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(I18nLanguageSnippetFromJSON));
    }

    /**
     */
    async apiLanguageYouTubeI18nLanguagesGet(): Promise<Array<I18nLanguageSnippet>> {
        const response = await this.apiLanguageYouTubeI18nLanguagesGetRaw();
        return await response.value();
    }

}
