/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ApiTranslationPostRequest {
    targetLanguageCode?: string | null;
    sourceLanguageCode?: string | null;
    body?: string | null;
}

/**
 * no description
 */
export class TranslationApi extends runtime.BaseAPI {

    /**
     */
    async apiTranslationPostRaw(requestParameters: ApiTranslationPostRequest): Promise<runtime.ApiResponse<string>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.targetLanguageCode !== undefined) {
            queryParameters['targetLanguageCode'] = requestParameters.targetLanguageCode;
        }

        if (requestParameters.sourceLanguageCode !== undefined) {
            queryParameters['sourceLanguageCode'] = requestParameters.sourceLanguageCode;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Translation`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async apiTranslationPost(requestParameters: ApiTranslationPostRequest): Promise<string> {
        const response = await this.apiTranslationPostRaw(requestParameters);
        return await response.value();
    }

}
