/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AppVideoLocalizeRequest,
    AppVideoLocalizeRequestFromJSON,
    AppVideoLocalizeRequestToJSON,
} from '../models';

export interface ApiYouTubeVideoLocalizationCountGetRequest {
    hash?: string | null;
}

export interface ApiYouTubeVideoLocalizePutRequest {
    appVideoLocalizeRequest: AppVideoLocalizeRequest;
}

/**
 * no description
 */
export class YouTubeVideoApi extends runtime.BaseAPI {

    /**
     */
    async apiYouTubeVideoLocalizationCountGetRaw(requestParameters: ApiYouTubeVideoLocalizationCountGetRequest): Promise<runtime.ApiResponse<number>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.hash !== undefined) {
            queryParameters['hash'] = requestParameters.hash;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/YouTubeVideo/LocalizationCount`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async apiYouTubeVideoLocalizationCountGet(requestParameters: ApiYouTubeVideoLocalizationCountGetRequest): Promise<number> {
        const response = await this.apiYouTubeVideoLocalizationCountGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async apiYouTubeVideoLocalizePutRaw(requestParameters: ApiYouTubeVideoLocalizePutRequest): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.appVideoLocalizeRequest === null || requestParameters.appVideoLocalizeRequest === undefined) {
            throw new runtime.RequiredError('appVideoLocalizeRequest','Required parameter requestParameters.appVideoLocalizeRequest was null or undefined when calling apiYouTubeVideoLocalizePut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/YouTubeVideo/Localize`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AppVideoLocalizeRequestToJSON(requestParameters.appVideoLocalizeRequest),
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async apiYouTubeVideoLocalizePut(requestParameters: ApiYouTubeVideoLocalizePutRequest): Promise<string> {
        const response = await this.apiYouTubeVideoLocalizePutRaw(requestParameters);
        return await response.value();
    }

}
