/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AppPlaylistItemListRequest,
    AppPlaylistItemListRequestFromJSON,
    AppPlaylistItemListRequestToJSON,
    PlaylistItemListResponse,
    PlaylistItemListResponseFromJSON,
    PlaylistItemListResponseToJSON,
} from '../models';

export interface ApiYouTubePlaylistItemListGetRequest {
    appPlaylistItemListRequest: AppPlaylistItemListRequest;
}

/**
 * no description
 */
export class YouTubePlaylistItemApi extends runtime.BaseAPI {

    /**
     */
    async apiYouTubePlaylistItemListGetRaw(requestParameters: ApiYouTubePlaylistItemListGetRequest): Promise<runtime.ApiResponse<PlaylistItemListResponse>> {
        if (requestParameters.appPlaylistItemListRequest === null || requestParameters.appPlaylistItemListRequest === undefined) {
            throw new runtime.RequiredError('appPlaylistItemListRequest','Required parameter requestParameters.appPlaylistItemListRequest was null or undefined when calling apiYouTubePlaylistItemListGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/YouTubePlaylistItem/List`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: AppPlaylistItemListRequestToJSON(requestParameters.appPlaylistItemListRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistItemListResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiYouTubePlaylistItemListGet(requestParameters: ApiYouTubePlaylistItemListGetRequest): Promise<PlaylistItemListResponse> {
        const response = await this.apiYouTubePlaylistItemListGetRaw(requestParameters);
        return await response.value();
    }

}
