/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Video,
    VideoFromJSON,
    VideoFromJSONTyped,
    VideoToJSON,
} from './';

/**
 * 
 * @export
 * @interface AppAddLocalizationRequest
 */
export interface AppAddLocalizationRequest {
    /**
     * 
     * @type {Video}
     * @memberof AppAddLocalizationRequest
     */
    video?: Video;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppAddLocalizationRequest
     */
    languages?: Array<string> | null;
}

export function AppAddLocalizationRequestFromJSON(json: any): AppAddLocalizationRequest {
    return AppAddLocalizationRequestFromJSONTyped(json, false);
}

export function AppAddLocalizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAddLocalizationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'video': !exists(json, 'video') ? undefined : VideoFromJSON(json['video']),
        'languages': !exists(json, 'languages') ? undefined : json['languages'],
    };
}

export function AppAddLocalizationRequestToJSON(value?: AppAddLocalizationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'video': VideoToJSON(value.video),
        'languages': value.languages,
    };
}


