/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppChannelListRequest
 */
export interface AppChannelListRequest {
    /**
     * 
     * @type {string}
     * @memberof AppChannelListRequest
     */
    part?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppChannelListRequest
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppChannelListRequest
     */
    forUsername?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppChannelListRequest
     */
    hl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppChannelListRequest
     */
    id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AppChannelListRequest
     */
    managedByMe?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof AppChannelListRequest
     */
    maxResults?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AppChannelListRequest
     */
    mine?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AppChannelListRequest
     */
    mySubscribers?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AppChannelListRequest
     */
    onBehalfOfContentOwner?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppChannelListRequest
     */
    pageToken?: string | null;
}

export function AppChannelListRequestFromJSON(json: any): AppChannelListRequest {
    return AppChannelListRequestFromJSONTyped(json, false);
}

export function AppChannelListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppChannelListRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'part': !exists(json, 'part') ? undefined : json['part'],
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'forUsername': !exists(json, 'forUsername') ? undefined : json['forUsername'],
        'hl': !exists(json, 'hl') ? undefined : json['hl'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'managedByMe': !exists(json, 'managedByMe') ? undefined : json['managedByMe'],
        'maxResults': !exists(json, 'maxResults') ? undefined : json['maxResults'],
        'mine': !exists(json, 'mine') ? undefined : json['mine'],
        'mySubscribers': !exists(json, 'mySubscribers') ? undefined : json['mySubscribers'],
        'onBehalfOfContentOwner': !exists(json, 'onBehalfOfContentOwner') ? undefined : json['onBehalfOfContentOwner'],
        'pageToken': !exists(json, 'pageToken') ? undefined : json['pageToken'],
    };
}

export function AppChannelListRequestToJSON(value?: AppChannelListRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'part': value.part,
        'categoryId': value.categoryId,
        'forUsername': value.forUsername,
        'hl': value.hl,
        'id': value.id,
        'managedByMe': value.managedByMe,
        'maxResults': value.maxResults,
        'mine': value.mine,
        'mySubscribers': value.mySubscribers,
        'onBehalfOfContentOwner': value.onBehalfOfContentOwner,
        'pageToken': value.pageToken,
    };
}


