/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppPlaylistItemListRequest
 */
export interface AppPlaylistItemListRequest {
    /**
     * 
     * @type {string}
     * @memberof AppPlaylistItemListRequest
     */
    part?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppPlaylistItemListRequest
     */
    id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AppPlaylistItemListRequest
     */
    maxResults?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AppPlaylistItemListRequest
     */
    onBehalfOfContentOwner?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppPlaylistItemListRequest
     */
    pageToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppPlaylistItemListRequest
     */
    playlistId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppPlaylistItemListRequest
     */
    videoId?: string | null;
}

export function AppPlaylistItemListRequestFromJSON(json: any): AppPlaylistItemListRequest {
    return AppPlaylistItemListRequestFromJSONTyped(json, false);
}

export function AppPlaylistItemListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPlaylistItemListRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'part': !exists(json, 'part') ? undefined : json['part'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'maxResults': !exists(json, 'maxResults') ? undefined : json['maxResults'],
        'onBehalfOfContentOwner': !exists(json, 'onBehalfOfContentOwner') ? undefined : json['onBehalfOfContentOwner'],
        'pageToken': !exists(json, 'pageToken') ? undefined : json['pageToken'],
        'playlistId': !exists(json, 'playlistId') ? undefined : json['playlistId'],
        'videoId': !exists(json, 'videoId') ? undefined : json['videoId'],
    };
}

export function AppPlaylistItemListRequestToJSON(value?: AppPlaylistItemListRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'part': value.part,
        'id': value.id,
        'maxResults': value.maxResults,
        'onBehalfOfContentOwner': value.onBehalfOfContentOwner,
        'pageToken': value.pageToken,
        'playlistId': value.playlistId,
        'videoId': value.videoId,
    };
}


