/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSupportedLanguage
 */
export interface AppSupportedLanguage {
    /**
     * 
     * @type {string}
     * @memberof AppSupportedLanguage
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppSupportedLanguage
     */
    code: string;
}

export function AppSupportedLanguageFromJSON(json: any): AppSupportedLanguage {
    return AppSupportedLanguageFromJSONTyped(json, false);
}

export function AppSupportedLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSupportedLanguage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'code': json['code'],
    };
}

export function AppSupportedLanguageToJSON(value?: AppSupportedLanguage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'code': value.code,
    };
}


