/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppVideoLocalizeRequest
 */
export interface AppVideoLocalizeRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof AppVideoLocalizeRequest
     */
    mineChannelVideoUploadCollection: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppVideoLocalizeRequest
     */
    translationLanguageCollection: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AppVideoLocalizeRequest
     */
    nullifyVideoLocalizations?: boolean;
}

export function AppVideoLocalizeRequestFromJSON(json: any): AppVideoLocalizeRequest {
    return AppVideoLocalizeRequestFromJSONTyped(json, false);
}

export function AppVideoLocalizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppVideoLocalizeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mineChannelVideoUploadCollection': json['mineChannelVideoUploadCollection'],
        'translationLanguageCollection': json['translationLanguageCollection'],
        'nullifyVideoLocalizations': !exists(json, 'nullifyVideoLocalizations') ? undefined : json['nullifyVideoLocalizations'],
    };
}

export function AppVideoLocalizeRequestToJSON(value?: AppVideoLocalizeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mineChannelVideoUploadCollection': value.mineChannelVideoUploadCollection,
        'translationLanguageCollection': value.translationLanguageCollection,
        'nullifyVideoLocalizations': value.nullifyVideoLocalizations,
    };
}


