/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppVideoLocalizeRequest
 */
export interface AppVideoLocalizeRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof AppVideoLocalizeRequest
     */
    videos: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppVideoLocalizeRequest
     */
    languages: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AppVideoLocalizeRequest
     */
    sheetMusicBoss?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppVideoLocalizeRequest
     */
    excludeOtherLanguages?: boolean;
}

export function AppVideoLocalizeRequestFromJSON(json: any): AppVideoLocalizeRequest {
    return AppVideoLocalizeRequestFromJSONTyped(json, false);
}

export function AppVideoLocalizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppVideoLocalizeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'videos': json['videos'],
        'languages': json['languages'],
        'sheetMusicBoss': !exists(json, 'sheetMusicBoss') ? undefined : json['sheetMusicBoss'],
        'excludeOtherLanguages': !exists(json, 'excludeOtherLanguages') ? undefined : json['excludeOtherLanguages'],
    };
}

export function AppVideoLocalizeRequestToJSON(value?: AppVideoLocalizeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'videos': value.videos,
        'languages': value.languages,
        'sheetMusicBoss': value.sheetMusicBoss,
        'excludeOtherLanguages': value.excludeOtherLanguages,
    };
}


