/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelTopicDetails
 */
export interface ChannelTopicDetails {
    /**
     * 
     * @type {Array<string>}
     * @memberof ChannelTopicDetails
     */
    topicCategories?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChannelTopicDetails
     */
    topicIds?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelTopicDetails
     */
    eTag?: string | null;
}

export function ChannelTopicDetailsFromJSON(json: any): ChannelTopicDetails {
    return ChannelTopicDetailsFromJSONTyped(json, false);
}

export function ChannelTopicDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelTopicDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topicCategories': !exists(json, 'topicCategories') ? undefined : json['topicCategories'],
        'topicIds': !exists(json, 'topicIds') ? undefined : json['topicIds'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function ChannelTopicDetailsToJSON(value?: ChannelTopicDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topicCategories': value.topicCategories,
        'topicIds': value.topicIds,
        'eTag': value.eTag,
    };
}


