/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelAuditDetails
 */
export interface ChannelAuditDetails {
    /**
     * 
     * @type {boolean}
     * @memberof ChannelAuditDetails
     */
    communityGuidelinesGoodStanding?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelAuditDetails
     */
    contentIdClaimsGoodStanding?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelAuditDetails
     */
    copyrightStrikesGoodStanding?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelAuditDetails
     */
    eTag?: string | null;
}

export function ChannelAuditDetailsFromJSON(json: any): ChannelAuditDetails {
    return ChannelAuditDetailsFromJSONTyped(json, false);
}

export function ChannelAuditDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelAuditDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'communityGuidelinesGoodStanding': !exists(json, 'communityGuidelinesGoodStanding') ? undefined : json['communityGuidelinesGoodStanding'],
        'contentIdClaimsGoodStanding': !exists(json, 'contentIdClaimsGoodStanding') ? undefined : json['contentIdClaimsGoodStanding'],
        'copyrightStrikesGoodStanding': !exists(json, 'copyrightStrikesGoodStanding') ? undefined : json['copyrightStrikesGoodStanding'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function ChannelAuditDetailsToJSON(value?: ChannelAuditDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'communityGuidelinesGoodStanding': value.communityGuidelinesGoodStanding,
        'contentIdClaimsGoodStanding': value.contentIdClaimsGoodStanding,
        'copyrightStrikesGoodStanding': value.copyrightStrikesGoodStanding,
        'eTag': value.eTag,
    };
}


