/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelSettings
 */
export interface ChannelSettings {
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    defaultLanguage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    defaultTab?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    featuredChannelsTitle?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChannelSettings
     */
    featuredChannelsUrls?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    keywords?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelSettings
     */
    moderateComments?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    profileColor?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelSettings
     */
    showBrowseView?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelSettings
     */
    showRelatedChannels?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    trackingAnalyticsAccountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    unsubscribedTrailer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelSettings
     */
    eTag?: string | null;
}

export function ChannelSettingsFromJSON(json: any): ChannelSettings {
    return ChannelSettingsFromJSONTyped(json, false);
}

export function ChannelSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': !exists(json, 'country') ? undefined : json['country'],
        'defaultLanguage': !exists(json, 'defaultLanguage') ? undefined : json['defaultLanguage'],
        'defaultTab': !exists(json, 'defaultTab') ? undefined : json['defaultTab'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'featuredChannelsTitle': !exists(json, 'featuredChannelsTitle') ? undefined : json['featuredChannelsTitle'],
        'featuredChannelsUrls': !exists(json, 'featuredChannelsUrls') ? undefined : json['featuredChannelsUrls'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
        'moderateComments': !exists(json, 'moderateComments') ? undefined : json['moderateComments'],
        'profileColor': !exists(json, 'profileColor') ? undefined : json['profileColor'],
        'showBrowseView': !exists(json, 'showBrowseView') ? undefined : json['showBrowseView'],
        'showRelatedChannels': !exists(json, 'showRelatedChannels') ? undefined : json['showRelatedChannels'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'trackingAnalyticsAccountId': !exists(json, 'trackingAnalyticsAccountId') ? undefined : json['trackingAnalyticsAccountId'],
        'unsubscribedTrailer': !exists(json, 'unsubscribedTrailer') ? undefined : json['unsubscribedTrailer'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function ChannelSettingsToJSON(value?: ChannelSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'defaultLanguage': value.defaultLanguage,
        'defaultTab': value.defaultTab,
        'description': value.description,
        'featuredChannelsTitle': value.featuredChannelsTitle,
        'featuredChannelsUrls': value.featuredChannelsUrls,
        'keywords': value.keywords,
        'moderateComments': value.moderateComments,
        'profileColor': value.profileColor,
        'showBrowseView': value.showBrowseView,
        'showRelatedChannels': value.showRelatedChannels,
        'title': value.title,
        'trackingAnalyticsAccountId': value.trackingAnalyticsAccountId,
        'unsubscribedTrailer': value.unsubscribedTrailer,
        'eTag': value.eTag,
    };
}


