/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelContentOwnerDetails
 */
export interface ChannelContentOwnerDetails {
    /**
     * 
     * @type {string}
     * @memberof ChannelContentOwnerDetails
     */
    contentOwner?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelContentOwnerDetails
     */
    timeLinkedRaw?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ChannelContentOwnerDetails
     */
    timeLinked?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelContentOwnerDetails
     */
    eTag?: string | null;
}

export function ChannelContentOwnerDetailsFromJSON(json: any): ChannelContentOwnerDetails {
    return ChannelContentOwnerDetailsFromJSONTyped(json, false);
}

export function ChannelContentOwnerDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelContentOwnerDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentOwner': !exists(json, 'contentOwner') ? undefined : json['contentOwner'],
        'timeLinkedRaw': !exists(json, 'timeLinkedRaw') ? undefined : json['timeLinkedRaw'],
        'timeLinked': !exists(json, 'timeLinked') ? undefined : (json['timeLinked'] === null ? null : new Date(json['timeLinked'])),
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function ChannelContentOwnerDetailsToJSON(value?: ChannelContentOwnerDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentOwner': value.contentOwner,
        'timeLinkedRaw': value.timeLinkedRaw,
        'timeLinked': value.timeLinked === undefined ? undefined : (value.timeLinked === null ? null : value.timeLinked.toISOString()),
        'eTag': value.eTag,
    };
}


