/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RelatedPlaylistsData,
    RelatedPlaylistsDataFromJSON,
    RelatedPlaylistsDataFromJSONTyped,
    RelatedPlaylistsDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface ChannelContentDetails
 */
export interface ChannelContentDetails {
    /**
     * 
     * @type {RelatedPlaylistsData}
     * @memberof ChannelContentDetails
     */
    relatedPlaylists?: RelatedPlaylistsData;
    /**
     * 
     * @type {string}
     * @memberof ChannelContentDetails
     */
    eTag?: string | null;
}

export function ChannelContentDetailsFromJSON(json: any): ChannelContentDetails {
    return ChannelContentDetailsFromJSONTyped(json, false);
}

export function ChannelContentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelContentDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'relatedPlaylists': !exists(json, 'relatedPlaylists') ? undefined : RelatedPlaylistsDataFromJSON(json['relatedPlaylists']),
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function ChannelContentDetailsToJSON(value?: ChannelContentDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relatedPlaylists': RelatedPlaylistsDataToJSON(value.relatedPlaylists),
        'eTag': value.eTag,
    };
}


