/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentRating
 */
export interface ContentRating {
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    acbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    agcomRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    anatelRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    bbfcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    bfvcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    bmukkRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    catvRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    catvfrRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    cbfcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    cccRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    cceRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    chfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    chvrsRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    cicfRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    cnaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    cncRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    csaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    cscfRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    czfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    djctqRating?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentRating
     */
    djctqRatingReasons?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    ecbmctRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    eefilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    egfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    eirinRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    fcbmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    fcoRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    fmocRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    fpbRating?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentRating
     */
    fpbRatingReasons?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    fskRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    grfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    icaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    ifcoRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    ilfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    incaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    kfcbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    kijkwijzerRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    kmrbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    lsfRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mccaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mccypRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mcstRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mdaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    medietilsynetRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mekuRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    menaMpaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mibacRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mocRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    moctwRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mpaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mpaatRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    mtrcbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    nbcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    nbcplRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    nfrcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    nfvcbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    nkclvRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    nmcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    oflcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    pefilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    rcnofRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    resorteviolenciaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    rtcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    rteRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    russiaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    skfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    smaisRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    smsaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    tvpgRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    ytRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentRating
     */
    eTag?: string | null;
}

export function ContentRatingFromJSON(json: any): ContentRating {
    return ContentRatingFromJSONTyped(json, false);
}

export function ContentRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentRating {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'acbRating': !exists(json, 'acbRating') ? undefined : json['acbRating'],
        'agcomRating': !exists(json, 'agcomRating') ? undefined : json['agcomRating'],
        'anatelRating': !exists(json, 'anatelRating') ? undefined : json['anatelRating'],
        'bbfcRating': !exists(json, 'bbfcRating') ? undefined : json['bbfcRating'],
        'bfvcRating': !exists(json, 'bfvcRating') ? undefined : json['bfvcRating'],
        'bmukkRating': !exists(json, 'bmukkRating') ? undefined : json['bmukkRating'],
        'catvRating': !exists(json, 'catvRating') ? undefined : json['catvRating'],
        'catvfrRating': !exists(json, 'catvfrRating') ? undefined : json['catvfrRating'],
        'cbfcRating': !exists(json, 'cbfcRating') ? undefined : json['cbfcRating'],
        'cccRating': !exists(json, 'cccRating') ? undefined : json['cccRating'],
        'cceRating': !exists(json, 'cceRating') ? undefined : json['cceRating'],
        'chfilmRating': !exists(json, 'chfilmRating') ? undefined : json['chfilmRating'],
        'chvrsRating': !exists(json, 'chvrsRating') ? undefined : json['chvrsRating'],
        'cicfRating': !exists(json, 'cicfRating') ? undefined : json['cicfRating'],
        'cnaRating': !exists(json, 'cnaRating') ? undefined : json['cnaRating'],
        'cncRating': !exists(json, 'cncRating') ? undefined : json['cncRating'],
        'csaRating': !exists(json, 'csaRating') ? undefined : json['csaRating'],
        'cscfRating': !exists(json, 'cscfRating') ? undefined : json['cscfRating'],
        'czfilmRating': !exists(json, 'czfilmRating') ? undefined : json['czfilmRating'],
        'djctqRating': !exists(json, 'djctqRating') ? undefined : json['djctqRating'],
        'djctqRatingReasons': !exists(json, 'djctqRatingReasons') ? undefined : json['djctqRatingReasons'],
        'ecbmctRating': !exists(json, 'ecbmctRating') ? undefined : json['ecbmctRating'],
        'eefilmRating': !exists(json, 'eefilmRating') ? undefined : json['eefilmRating'],
        'egfilmRating': !exists(json, 'egfilmRating') ? undefined : json['egfilmRating'],
        'eirinRating': !exists(json, 'eirinRating') ? undefined : json['eirinRating'],
        'fcbmRating': !exists(json, 'fcbmRating') ? undefined : json['fcbmRating'],
        'fcoRating': !exists(json, 'fcoRating') ? undefined : json['fcoRating'],
        'fmocRating': !exists(json, 'fmocRating') ? undefined : json['fmocRating'],
        'fpbRating': !exists(json, 'fpbRating') ? undefined : json['fpbRating'],
        'fpbRatingReasons': !exists(json, 'fpbRatingReasons') ? undefined : json['fpbRatingReasons'],
        'fskRating': !exists(json, 'fskRating') ? undefined : json['fskRating'],
        'grfilmRating': !exists(json, 'grfilmRating') ? undefined : json['grfilmRating'],
        'icaaRating': !exists(json, 'icaaRating') ? undefined : json['icaaRating'],
        'ifcoRating': !exists(json, 'ifcoRating') ? undefined : json['ifcoRating'],
        'ilfilmRating': !exists(json, 'ilfilmRating') ? undefined : json['ilfilmRating'],
        'incaaRating': !exists(json, 'incaaRating') ? undefined : json['incaaRating'],
        'kfcbRating': !exists(json, 'kfcbRating') ? undefined : json['kfcbRating'],
        'kijkwijzerRating': !exists(json, 'kijkwijzerRating') ? undefined : json['kijkwijzerRating'],
        'kmrbRating': !exists(json, 'kmrbRating') ? undefined : json['kmrbRating'],
        'lsfRating': !exists(json, 'lsfRating') ? undefined : json['lsfRating'],
        'mccaaRating': !exists(json, 'mccaaRating') ? undefined : json['mccaaRating'],
        'mccypRating': !exists(json, 'mccypRating') ? undefined : json['mccypRating'],
        'mcstRating': !exists(json, 'mcstRating') ? undefined : json['mcstRating'],
        'mdaRating': !exists(json, 'mdaRating') ? undefined : json['mdaRating'],
        'medietilsynetRating': !exists(json, 'medietilsynetRating') ? undefined : json['medietilsynetRating'],
        'mekuRating': !exists(json, 'mekuRating') ? undefined : json['mekuRating'],
        'menaMpaaRating': !exists(json, 'menaMpaaRating') ? undefined : json['menaMpaaRating'],
        'mibacRating': !exists(json, 'mibacRating') ? undefined : json['mibacRating'],
        'mocRating': !exists(json, 'mocRating') ? undefined : json['mocRating'],
        'moctwRating': !exists(json, 'moctwRating') ? undefined : json['moctwRating'],
        'mpaaRating': !exists(json, 'mpaaRating') ? undefined : json['mpaaRating'],
        'mpaatRating': !exists(json, 'mpaatRating') ? undefined : json['mpaatRating'],
        'mtrcbRating': !exists(json, 'mtrcbRating') ? undefined : json['mtrcbRating'],
        'nbcRating': !exists(json, 'nbcRating') ? undefined : json['nbcRating'],
        'nbcplRating': !exists(json, 'nbcplRating') ? undefined : json['nbcplRating'],
        'nfrcRating': !exists(json, 'nfrcRating') ? undefined : json['nfrcRating'],
        'nfvcbRating': !exists(json, 'nfvcbRating') ? undefined : json['nfvcbRating'],
        'nkclvRating': !exists(json, 'nkclvRating') ? undefined : json['nkclvRating'],
        'nmcRating': !exists(json, 'nmcRating') ? undefined : json['nmcRating'],
        'oflcRating': !exists(json, 'oflcRating') ? undefined : json['oflcRating'],
        'pefilmRating': !exists(json, 'pefilmRating') ? undefined : json['pefilmRating'],
        'rcnofRating': !exists(json, 'rcnofRating') ? undefined : json['rcnofRating'],
        'resorteviolenciaRating': !exists(json, 'resorteviolenciaRating') ? undefined : json['resorteviolenciaRating'],
        'rtcRating': !exists(json, 'rtcRating') ? undefined : json['rtcRating'],
        'rteRating': !exists(json, 'rteRating') ? undefined : json['rteRating'],
        'russiaRating': !exists(json, 'russiaRating') ? undefined : json['russiaRating'],
        'skfilmRating': !exists(json, 'skfilmRating') ? undefined : json['skfilmRating'],
        'smaisRating': !exists(json, 'smaisRating') ? undefined : json['smaisRating'],
        'smsaRating': !exists(json, 'smsaRating') ? undefined : json['smsaRating'],
        'tvpgRating': !exists(json, 'tvpgRating') ? undefined : json['tvpgRating'],
        'ytRating': !exists(json, 'ytRating') ? undefined : json['ytRating'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function ContentRatingToJSON(value?: ContentRating | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'acbRating': value.acbRating,
        'agcomRating': value.agcomRating,
        'anatelRating': value.anatelRating,
        'bbfcRating': value.bbfcRating,
        'bfvcRating': value.bfvcRating,
        'bmukkRating': value.bmukkRating,
        'catvRating': value.catvRating,
        'catvfrRating': value.catvfrRating,
        'cbfcRating': value.cbfcRating,
        'cccRating': value.cccRating,
        'cceRating': value.cceRating,
        'chfilmRating': value.chfilmRating,
        'chvrsRating': value.chvrsRating,
        'cicfRating': value.cicfRating,
        'cnaRating': value.cnaRating,
        'cncRating': value.cncRating,
        'csaRating': value.csaRating,
        'cscfRating': value.cscfRating,
        'czfilmRating': value.czfilmRating,
        'djctqRating': value.djctqRating,
        'djctqRatingReasons': value.djctqRatingReasons,
        'ecbmctRating': value.ecbmctRating,
        'eefilmRating': value.eefilmRating,
        'egfilmRating': value.egfilmRating,
        'eirinRating': value.eirinRating,
        'fcbmRating': value.fcbmRating,
        'fcoRating': value.fcoRating,
        'fmocRating': value.fmocRating,
        'fpbRating': value.fpbRating,
        'fpbRatingReasons': value.fpbRatingReasons,
        'fskRating': value.fskRating,
        'grfilmRating': value.grfilmRating,
        'icaaRating': value.icaaRating,
        'ifcoRating': value.ifcoRating,
        'ilfilmRating': value.ilfilmRating,
        'incaaRating': value.incaaRating,
        'kfcbRating': value.kfcbRating,
        'kijkwijzerRating': value.kijkwijzerRating,
        'kmrbRating': value.kmrbRating,
        'lsfRating': value.lsfRating,
        'mccaaRating': value.mccaaRating,
        'mccypRating': value.mccypRating,
        'mcstRating': value.mcstRating,
        'mdaRating': value.mdaRating,
        'medietilsynetRating': value.medietilsynetRating,
        'mekuRating': value.mekuRating,
        'menaMpaaRating': value.menaMpaaRating,
        'mibacRating': value.mibacRating,
        'mocRating': value.mocRating,
        'moctwRating': value.moctwRating,
        'mpaaRating': value.mpaaRating,
        'mpaatRating': value.mpaatRating,
        'mtrcbRating': value.mtrcbRating,
        'nbcRating': value.nbcRating,
        'nbcplRating': value.nbcplRating,
        'nfrcRating': value.nfrcRating,
        'nfvcbRating': value.nfvcbRating,
        'nkclvRating': value.nkclvRating,
        'nmcRating': value.nmcRating,
        'oflcRating': value.oflcRating,
        'pefilmRating': value.pefilmRating,
        'rcnofRating': value.rcnofRating,
        'resorteviolenciaRating': value.resorteviolenciaRating,
        'rtcRating': value.rtcRating,
        'rteRating': value.rteRating,
        'russiaRating': value.russiaRating,
        'skfilmRating': value.skfilmRating,
        'smaisRating': value.smaisRating,
        'smsaRating': value.smsaRating,
        'tvpgRating': value.tvpgRating,
        'ytRating': value.ytRating,
        'eTag': value.eTag,
    };
}


