/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoPoint
 */
export interface GeoPoint {
    /**
     * 
     * @type {number}
     * @memberof GeoPoint
     */
    altitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GeoPoint
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GeoPoint
     */
    longitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GeoPoint
     */
    eTag?: string | null;
}

export function GeoPointFromJSON(json: any): GeoPoint {
    return GeoPointFromJSONTyped(json, false);
}

export function GeoPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoPoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'altitude': !exists(json, 'altitude') ? undefined : json['altitude'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function GeoPointToJSON(value?: GeoPoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'altitude': value.altitude,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'eTag': value.eTag,
    };
}


