/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Claim,
    ClaimFromJSON,
    ClaimFromJSONTyped,
    ClaimToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetClaimsPrincipleResult
 */
export interface GetClaimsPrincipleResult {
    /**
     * 
     * @type {Array<Claim>}
     * @memberof GetClaimsPrincipleResult
     */
    claims?: Array<Claim> | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetClaimsPrincipleResult
     */
    isAuthenticated?: boolean;
}

export function GetClaimsPrincipleResultFromJSON(json: any): GetClaimsPrincipleResult {
    return GetClaimsPrincipleResultFromJSONTyped(json, false);
}

export function GetClaimsPrincipleResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClaimsPrincipleResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'claims': !exists(json, 'claims') ? undefined : (json['claims'] === null ? null : (json['claims'] as Array<any>).map(ClaimFromJSON)),
        'isAuthenticated': !exists(json, 'isAuthenticated') ? undefined : json['isAuthenticated'],
    };
}

export function GetClaimsPrincipleResultToJSON(value?: GetClaimsPrincipleResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'claims': value.claims === undefined ? undefined : (value.claims === null ? null : (value.claims as Array<any>).map(ClaimToJSON)),
        'isAuthenticated': value.isAuthenticated,
    };
}


