/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface I18nLanguageSnippet
 */
export interface I18nLanguageSnippet {
    /**
     * 
     * @type {string}
     * @memberof I18nLanguageSnippet
     */
    hl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof I18nLanguageSnippet
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof I18nLanguageSnippet
     */
    eTag?: string | null;
}

export function I18nLanguageSnippetFromJSON(json: any): I18nLanguageSnippet {
    return I18nLanguageSnippetFromJSONTyped(json, false);
}

export function I18nLanguageSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): I18nLanguageSnippet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hl': !exists(json, 'hl') ? undefined : json['hl'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function I18nLanguageSnippetToJSON(value?: I18nLanguageSnippet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hl': value.hl,
        'name': value.name,
        'eTag': value.eTag,
    };
}


