/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    I18nLanguage,
    I18nLanguageFromJSON,
    I18nLanguageFromJSONTyped,
    I18nLanguageToJSON,
} from './';

/**
 * 
 * @export
 * @interface I18nLanguageListResponse
 */
export interface I18nLanguageListResponse {
    /**
     * 
     * @type {string}
     * @memberof I18nLanguageListResponse
     */
    eTag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof I18nLanguageListResponse
     */
    eventId?: string | null;
    /**
     * 
     * @type {Array<I18nLanguage>}
     * @memberof I18nLanguageListResponse
     */
    items?: Array<I18nLanguage> | null;
    /**
     * 
     * @type {string}
     * @memberof I18nLanguageListResponse
     */
    kind?: string | null;
    /**
     * 
     * @type {string}
     * @memberof I18nLanguageListResponse
     */
    visitorId?: string | null;
}

export function I18nLanguageListResponseFromJSON(json: any): I18nLanguageListResponse {
    return I18nLanguageListResponseFromJSONTyped(json, false);
}

export function I18nLanguageListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): I18nLanguageListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
        'eventId': !exists(json, 'eventId') ? undefined : json['eventId'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(I18nLanguageFromJSON)),
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'visitorId': !exists(json, 'visitorId') ? undefined : json['visitorId'],
    };
}

export function I18nLanguageListResponseToJSON(value?: I18nLanguageListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eTag': value.eTag,
        'eventId': value.eventId,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(I18nLanguageToJSON)),
        'kind': value.kind,
        'visitorId': value.visitorId,
    };
}


