/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    VideoFileDetailsAudioStream,
    VideoFileDetailsAudioStreamFromJSON,
    VideoFileDetailsAudioStreamFromJSONTyped,
    VideoFileDetailsAudioStreamToJSON,
    VideoFileDetailsVideoStream,
    VideoFileDetailsVideoStreamFromJSON,
    VideoFileDetailsVideoStreamFromJSONTyped,
    VideoFileDetailsVideoStreamToJSON,
    VideoLocalization,
    VideoLocalizationFromJSON,
    VideoLocalizationFromJSONTyped,
    VideoLocalizationToJSON,
    VideoSuggestionsTagSuggestion,
    VideoSuggestionsTagSuggestionFromJSON,
    VideoSuggestionsTagSuggestionFromJSONTyped,
    VideoSuggestionsTagSuggestionToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    ageGatingAlcoholContent?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    ageGatingRestricted?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    ageGatingVideoGameRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    ageGatingETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsCaption?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingAcbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingAgcomRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingAnatelRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingBbfcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingBfvcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingBmukkRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCatvRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCatvfrRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCbfcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCccRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCceRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingChfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingChvrsRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCicfRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCnaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCncRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCsaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCscfRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingCzfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingDjctqRating?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    contentDetailsContentRatingDjctqRatingReasons?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingEcbmctRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingEefilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingEgfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingEirinRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingFcbmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingFcoRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingFmocRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingFpbRating?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    contentDetailsContentRatingFpbRatingReasons?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingFskRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingGrfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingIcaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingIfcoRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingIlfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingIncaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingKfcbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingKijkwijzerRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingKmrbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingLsfRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMccaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMccypRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMcstRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMdaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMedietilsynetRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMekuRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMenaMpaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMibacRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMocRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMoctwRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMpaaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMpaatRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingMtrcbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingNbcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingNbcplRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingNfrcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingNfvcbRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingNkclvRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingNmcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingOflcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingPefilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingRcnofRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingResorteviolenciaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingRtcRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingRteRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingRussiaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingSkfilmRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingSmaisRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingSmsaRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingTvpgRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingYtRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsContentRatingETag?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    contentDetailsCountryRestrictionAllowed?: boolean | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    contentDetailsCountryRestrictionException?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsCountryRestrictionETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsDefinition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsDimension?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsDuration?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    contentDetailsHasCustomThumbnail?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    contentDetailsLicensedContent?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsProjection?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    contentDetailsRegionRestrictionAllowed?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    contentDetailsRegionRestrictionBlocked?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsRegionRestrictionETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    contentDetailsETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    eTag?: string | null;
    /**
     * 
     * @type {Array<VideoFileDetailsAudioStream>}
     * @memberof InlineObject
     */
    fileDetailsAudioStreams?: Array<VideoFileDetailsAudioStream> | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    fileDetailsBitrateBps?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    fileDetailsContainer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    fileDetailsCreationTime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    fileDetailsDurationMs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    fileDetailsFileName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    fileDetailsFileSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    fileDetailsFileType?: string | null;
    /**
     * 
     * @type {Array<VideoFileDetailsVideoStream>}
     * @memberof InlineObject
     */
    fileDetailsVideoStreams?: Array<VideoFileDetailsVideoStream> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    fileDetailsETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    kind?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    liveStreamingDetailsActiveLiveChatId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    liveStreamingDetailsActualEndTimeRaw?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InlineObject
     */
    liveStreamingDetailsActualEndTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    liveStreamingDetailsActualStartTimeRaw?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InlineObject
     */
    liveStreamingDetailsActualStartTime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    liveStreamingDetailsConcurrentViewers?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    liveStreamingDetailsScheduledEndTimeRaw?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InlineObject
     */
    liveStreamingDetailsScheduledEndTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    liveStreamingDetailsScheduledStartTimeRaw?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InlineObject
     */
    liveStreamingDetailsScheduledStartTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    liveStreamingDetailsETag?: string | null;
    /**
     * 
     * @type {{ [key: string]: VideoLocalization; }}
     * @memberof InlineObject
     */
    localizations?: { [key: string]: VideoLocalization; } | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    monetizationDetailsAccessAllowed?: boolean | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    monetizationDetailsAccessException?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    monetizationDetailsAccessETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    monetizationDetailsETag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    playerEmbedHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    playerEmbedHtml?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    playerEmbedWidth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    playerETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsEditorSuggestionsAvailability?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsFileDetailsAvailability?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsProcessingFailureReason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsProcessingIssuesAvailability?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    processingDetailsProcessingProgressPartsProcessed?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    processingDetailsProcessingProgressPartsTotal?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    processingDetailsProcessingProgressTimeLeftMs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsProcessingProgressETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsProcessingStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsTagSuggestionsAvailability?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsThumbnailsAvailability?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    processingDetailsETag?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    projectDetailsTags?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    projectDetailsETag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    recordingDetailsLocationAltitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    recordingDetailsLocationLatitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    recordingDetailsLocationLongitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    recordingDetailsLocationETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    recordingDetailsLocationDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    recordingDetailsRecordingDateRaw?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InlineObject
     */
    recordingDetailsRecordingDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    recordingDetailsETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetCategoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetChannelId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetChannelTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetDefaultAudioLanguage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetDefaultLanguage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetLiveBroadcastContent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetLocalizedDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetLocalizedTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetLocalizedETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetPublishedAtRaw?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InlineObject
     */
    snippetPublishedAt?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    snippetTags?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsDefaultHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsDefaultUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsDefaultWidth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsDefaultETag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsHighHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsHighUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsHighWidth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsHighETag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsMaxresHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsMaxresUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsMaxresWidth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsMaxresETag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsMediumHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsMediumUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsMediumWidth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsMediumETag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsStandardHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsStandardUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    snippetThumbnailsStandardWidth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsStandardETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetThumbnailsETag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    snippetETag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    statisticsCommentCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    statisticsDislikeCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    statisticsFavoriteCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    statisticsLikeCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    statisticsViewCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    statisticsETag?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    statusEmbeddable?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    statusFailureReason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    statusLicense?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    statusMadeForKids?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    statusPrivacyStatus?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    statusPublicStatsViewable?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    statusPublishAtRaw?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InlineObject
     */
    statusPublishAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    statusRejectionReason?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    statusSelfDeclaredMadeForKids?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    statusUploadStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    statusETag?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    suggestionsEditorSuggestions?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    suggestionsProcessingErrors?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    suggestionsProcessingHints?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    suggestionsProcessingWarnings?: Array<string> | null;
    /**
     * 
     * @type {Array<VideoSuggestionsTagSuggestion>}
     * @memberof InlineObject
     */
    suggestionsTagSuggestions?: Array<VideoSuggestionsTagSuggestion> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    suggestionsETag?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    topicDetailsRelevantTopicIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    topicDetailsTopicCategories?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    topicDetailsTopicIds?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    topicDetailsETag?: string | null;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ageGatingAlcoholContent': !exists(json, 'AgeGating.AlcoholContent') ? undefined : json['AgeGating.AlcoholContent'],
        'ageGatingRestricted': !exists(json, 'AgeGating.Restricted') ? undefined : json['AgeGating.Restricted'],
        'ageGatingVideoGameRating': !exists(json, 'AgeGating.VideoGameRating') ? undefined : json['AgeGating.VideoGameRating'],
        'ageGatingETag': !exists(json, 'AgeGating.ETag') ? undefined : json['AgeGating.ETag'],
        'contentDetailsCaption': !exists(json, 'ContentDetails.Caption') ? undefined : json['ContentDetails.Caption'],
        'contentDetailsContentRatingAcbRating': !exists(json, 'ContentDetails.ContentRating.AcbRating') ? undefined : json['ContentDetails.ContentRating.AcbRating'],
        'contentDetailsContentRatingAgcomRating': !exists(json, 'ContentDetails.ContentRating.AgcomRating') ? undefined : json['ContentDetails.ContentRating.AgcomRating'],
        'contentDetailsContentRatingAnatelRating': !exists(json, 'ContentDetails.ContentRating.AnatelRating') ? undefined : json['ContentDetails.ContentRating.AnatelRating'],
        'contentDetailsContentRatingBbfcRating': !exists(json, 'ContentDetails.ContentRating.BbfcRating') ? undefined : json['ContentDetails.ContentRating.BbfcRating'],
        'contentDetailsContentRatingBfvcRating': !exists(json, 'ContentDetails.ContentRating.BfvcRating') ? undefined : json['ContentDetails.ContentRating.BfvcRating'],
        'contentDetailsContentRatingBmukkRating': !exists(json, 'ContentDetails.ContentRating.BmukkRating') ? undefined : json['ContentDetails.ContentRating.BmukkRating'],
        'contentDetailsContentRatingCatvRating': !exists(json, 'ContentDetails.ContentRating.CatvRating') ? undefined : json['ContentDetails.ContentRating.CatvRating'],
        'contentDetailsContentRatingCatvfrRating': !exists(json, 'ContentDetails.ContentRating.CatvfrRating') ? undefined : json['ContentDetails.ContentRating.CatvfrRating'],
        'contentDetailsContentRatingCbfcRating': !exists(json, 'ContentDetails.ContentRating.CbfcRating') ? undefined : json['ContentDetails.ContentRating.CbfcRating'],
        'contentDetailsContentRatingCccRating': !exists(json, 'ContentDetails.ContentRating.CccRating') ? undefined : json['ContentDetails.ContentRating.CccRating'],
        'contentDetailsContentRatingCceRating': !exists(json, 'ContentDetails.ContentRating.CceRating') ? undefined : json['ContentDetails.ContentRating.CceRating'],
        'contentDetailsContentRatingChfilmRating': !exists(json, 'ContentDetails.ContentRating.ChfilmRating') ? undefined : json['ContentDetails.ContentRating.ChfilmRating'],
        'contentDetailsContentRatingChvrsRating': !exists(json, 'ContentDetails.ContentRating.ChvrsRating') ? undefined : json['ContentDetails.ContentRating.ChvrsRating'],
        'contentDetailsContentRatingCicfRating': !exists(json, 'ContentDetails.ContentRating.CicfRating') ? undefined : json['ContentDetails.ContentRating.CicfRating'],
        'contentDetailsContentRatingCnaRating': !exists(json, 'ContentDetails.ContentRating.CnaRating') ? undefined : json['ContentDetails.ContentRating.CnaRating'],
        'contentDetailsContentRatingCncRating': !exists(json, 'ContentDetails.ContentRating.CncRating') ? undefined : json['ContentDetails.ContentRating.CncRating'],
        'contentDetailsContentRatingCsaRating': !exists(json, 'ContentDetails.ContentRating.CsaRating') ? undefined : json['ContentDetails.ContentRating.CsaRating'],
        'contentDetailsContentRatingCscfRating': !exists(json, 'ContentDetails.ContentRating.CscfRating') ? undefined : json['ContentDetails.ContentRating.CscfRating'],
        'contentDetailsContentRatingCzfilmRating': !exists(json, 'ContentDetails.ContentRating.CzfilmRating') ? undefined : json['ContentDetails.ContentRating.CzfilmRating'],
        'contentDetailsContentRatingDjctqRating': !exists(json, 'ContentDetails.ContentRating.DjctqRating') ? undefined : json['ContentDetails.ContentRating.DjctqRating'],
        'contentDetailsContentRatingDjctqRatingReasons': !exists(json, 'ContentDetails.ContentRating.DjctqRatingReasons') ? undefined : json['ContentDetails.ContentRating.DjctqRatingReasons'],
        'contentDetailsContentRatingEcbmctRating': !exists(json, 'ContentDetails.ContentRating.EcbmctRating') ? undefined : json['ContentDetails.ContentRating.EcbmctRating'],
        'contentDetailsContentRatingEefilmRating': !exists(json, 'ContentDetails.ContentRating.EefilmRating') ? undefined : json['ContentDetails.ContentRating.EefilmRating'],
        'contentDetailsContentRatingEgfilmRating': !exists(json, 'ContentDetails.ContentRating.EgfilmRating') ? undefined : json['ContentDetails.ContentRating.EgfilmRating'],
        'contentDetailsContentRatingEirinRating': !exists(json, 'ContentDetails.ContentRating.EirinRating') ? undefined : json['ContentDetails.ContentRating.EirinRating'],
        'contentDetailsContentRatingFcbmRating': !exists(json, 'ContentDetails.ContentRating.FcbmRating') ? undefined : json['ContentDetails.ContentRating.FcbmRating'],
        'contentDetailsContentRatingFcoRating': !exists(json, 'ContentDetails.ContentRating.FcoRating') ? undefined : json['ContentDetails.ContentRating.FcoRating'],
        'contentDetailsContentRatingFmocRating': !exists(json, 'ContentDetails.ContentRating.FmocRating') ? undefined : json['ContentDetails.ContentRating.FmocRating'],
        'contentDetailsContentRatingFpbRating': !exists(json, 'ContentDetails.ContentRating.FpbRating') ? undefined : json['ContentDetails.ContentRating.FpbRating'],
        'contentDetailsContentRatingFpbRatingReasons': !exists(json, 'ContentDetails.ContentRating.FpbRatingReasons') ? undefined : json['ContentDetails.ContentRating.FpbRatingReasons'],
        'contentDetailsContentRatingFskRating': !exists(json, 'ContentDetails.ContentRating.FskRating') ? undefined : json['ContentDetails.ContentRating.FskRating'],
        'contentDetailsContentRatingGrfilmRating': !exists(json, 'ContentDetails.ContentRating.GrfilmRating') ? undefined : json['ContentDetails.ContentRating.GrfilmRating'],
        'contentDetailsContentRatingIcaaRating': !exists(json, 'ContentDetails.ContentRating.IcaaRating') ? undefined : json['ContentDetails.ContentRating.IcaaRating'],
        'contentDetailsContentRatingIfcoRating': !exists(json, 'ContentDetails.ContentRating.IfcoRating') ? undefined : json['ContentDetails.ContentRating.IfcoRating'],
        'contentDetailsContentRatingIlfilmRating': !exists(json, 'ContentDetails.ContentRating.IlfilmRating') ? undefined : json['ContentDetails.ContentRating.IlfilmRating'],
        'contentDetailsContentRatingIncaaRating': !exists(json, 'ContentDetails.ContentRating.IncaaRating') ? undefined : json['ContentDetails.ContentRating.IncaaRating'],
        'contentDetailsContentRatingKfcbRating': !exists(json, 'ContentDetails.ContentRating.KfcbRating') ? undefined : json['ContentDetails.ContentRating.KfcbRating'],
        'contentDetailsContentRatingKijkwijzerRating': !exists(json, 'ContentDetails.ContentRating.KijkwijzerRating') ? undefined : json['ContentDetails.ContentRating.KijkwijzerRating'],
        'contentDetailsContentRatingKmrbRating': !exists(json, 'ContentDetails.ContentRating.KmrbRating') ? undefined : json['ContentDetails.ContentRating.KmrbRating'],
        'contentDetailsContentRatingLsfRating': !exists(json, 'ContentDetails.ContentRating.LsfRating') ? undefined : json['ContentDetails.ContentRating.LsfRating'],
        'contentDetailsContentRatingMccaaRating': !exists(json, 'ContentDetails.ContentRating.MccaaRating') ? undefined : json['ContentDetails.ContentRating.MccaaRating'],
        'contentDetailsContentRatingMccypRating': !exists(json, 'ContentDetails.ContentRating.MccypRating') ? undefined : json['ContentDetails.ContentRating.MccypRating'],
        'contentDetailsContentRatingMcstRating': !exists(json, 'ContentDetails.ContentRating.McstRating') ? undefined : json['ContentDetails.ContentRating.McstRating'],
        'contentDetailsContentRatingMdaRating': !exists(json, 'ContentDetails.ContentRating.MdaRating') ? undefined : json['ContentDetails.ContentRating.MdaRating'],
        'contentDetailsContentRatingMedietilsynetRating': !exists(json, 'ContentDetails.ContentRating.MedietilsynetRating') ? undefined : json['ContentDetails.ContentRating.MedietilsynetRating'],
        'contentDetailsContentRatingMekuRating': !exists(json, 'ContentDetails.ContentRating.MekuRating') ? undefined : json['ContentDetails.ContentRating.MekuRating'],
        'contentDetailsContentRatingMenaMpaaRating': !exists(json, 'ContentDetails.ContentRating.MenaMpaaRating') ? undefined : json['ContentDetails.ContentRating.MenaMpaaRating'],
        'contentDetailsContentRatingMibacRating': !exists(json, 'ContentDetails.ContentRating.MibacRating') ? undefined : json['ContentDetails.ContentRating.MibacRating'],
        'contentDetailsContentRatingMocRating': !exists(json, 'ContentDetails.ContentRating.MocRating') ? undefined : json['ContentDetails.ContentRating.MocRating'],
        'contentDetailsContentRatingMoctwRating': !exists(json, 'ContentDetails.ContentRating.MoctwRating') ? undefined : json['ContentDetails.ContentRating.MoctwRating'],
        'contentDetailsContentRatingMpaaRating': !exists(json, 'ContentDetails.ContentRating.MpaaRating') ? undefined : json['ContentDetails.ContentRating.MpaaRating'],
        'contentDetailsContentRatingMpaatRating': !exists(json, 'ContentDetails.ContentRating.MpaatRating') ? undefined : json['ContentDetails.ContentRating.MpaatRating'],
        'contentDetailsContentRatingMtrcbRating': !exists(json, 'ContentDetails.ContentRating.MtrcbRating') ? undefined : json['ContentDetails.ContentRating.MtrcbRating'],
        'contentDetailsContentRatingNbcRating': !exists(json, 'ContentDetails.ContentRating.NbcRating') ? undefined : json['ContentDetails.ContentRating.NbcRating'],
        'contentDetailsContentRatingNbcplRating': !exists(json, 'ContentDetails.ContentRating.NbcplRating') ? undefined : json['ContentDetails.ContentRating.NbcplRating'],
        'contentDetailsContentRatingNfrcRating': !exists(json, 'ContentDetails.ContentRating.NfrcRating') ? undefined : json['ContentDetails.ContentRating.NfrcRating'],
        'contentDetailsContentRatingNfvcbRating': !exists(json, 'ContentDetails.ContentRating.NfvcbRating') ? undefined : json['ContentDetails.ContentRating.NfvcbRating'],
        'contentDetailsContentRatingNkclvRating': !exists(json, 'ContentDetails.ContentRating.NkclvRating') ? undefined : json['ContentDetails.ContentRating.NkclvRating'],
        'contentDetailsContentRatingNmcRating': !exists(json, 'ContentDetails.ContentRating.NmcRating') ? undefined : json['ContentDetails.ContentRating.NmcRating'],
        'contentDetailsContentRatingOflcRating': !exists(json, 'ContentDetails.ContentRating.OflcRating') ? undefined : json['ContentDetails.ContentRating.OflcRating'],
        'contentDetailsContentRatingPefilmRating': !exists(json, 'ContentDetails.ContentRating.PefilmRating') ? undefined : json['ContentDetails.ContentRating.PefilmRating'],
        'contentDetailsContentRatingRcnofRating': !exists(json, 'ContentDetails.ContentRating.RcnofRating') ? undefined : json['ContentDetails.ContentRating.RcnofRating'],
        'contentDetailsContentRatingResorteviolenciaRating': !exists(json, 'ContentDetails.ContentRating.ResorteviolenciaRating') ? undefined : json['ContentDetails.ContentRating.ResorteviolenciaRating'],
        'contentDetailsContentRatingRtcRating': !exists(json, 'ContentDetails.ContentRating.RtcRating') ? undefined : json['ContentDetails.ContentRating.RtcRating'],
        'contentDetailsContentRatingRteRating': !exists(json, 'ContentDetails.ContentRating.RteRating') ? undefined : json['ContentDetails.ContentRating.RteRating'],
        'contentDetailsContentRatingRussiaRating': !exists(json, 'ContentDetails.ContentRating.RussiaRating') ? undefined : json['ContentDetails.ContentRating.RussiaRating'],
        'contentDetailsContentRatingSkfilmRating': !exists(json, 'ContentDetails.ContentRating.SkfilmRating') ? undefined : json['ContentDetails.ContentRating.SkfilmRating'],
        'contentDetailsContentRatingSmaisRating': !exists(json, 'ContentDetails.ContentRating.SmaisRating') ? undefined : json['ContentDetails.ContentRating.SmaisRating'],
        'contentDetailsContentRatingSmsaRating': !exists(json, 'ContentDetails.ContentRating.SmsaRating') ? undefined : json['ContentDetails.ContentRating.SmsaRating'],
        'contentDetailsContentRatingTvpgRating': !exists(json, 'ContentDetails.ContentRating.TvpgRating') ? undefined : json['ContentDetails.ContentRating.TvpgRating'],
        'contentDetailsContentRatingYtRating': !exists(json, 'ContentDetails.ContentRating.YtRating') ? undefined : json['ContentDetails.ContentRating.YtRating'],
        'contentDetailsContentRatingETag': !exists(json, 'ContentDetails.ContentRating.ETag') ? undefined : json['ContentDetails.ContentRating.ETag'],
        'contentDetailsCountryRestrictionAllowed': !exists(json, 'ContentDetails.CountryRestriction.Allowed') ? undefined : json['ContentDetails.CountryRestriction.Allowed'],
        'contentDetailsCountryRestrictionException': !exists(json, 'ContentDetails.CountryRestriction.Exception') ? undefined : json['ContentDetails.CountryRestriction.Exception'],
        'contentDetailsCountryRestrictionETag': !exists(json, 'ContentDetails.CountryRestriction.ETag') ? undefined : json['ContentDetails.CountryRestriction.ETag'],
        'contentDetailsDefinition': !exists(json, 'ContentDetails.Definition') ? undefined : json['ContentDetails.Definition'],
        'contentDetailsDimension': !exists(json, 'ContentDetails.Dimension') ? undefined : json['ContentDetails.Dimension'],
        'contentDetailsDuration': !exists(json, 'ContentDetails.Duration') ? undefined : json['ContentDetails.Duration'],
        'contentDetailsHasCustomThumbnail': !exists(json, 'ContentDetails.HasCustomThumbnail') ? undefined : json['ContentDetails.HasCustomThumbnail'],
        'contentDetailsLicensedContent': !exists(json, 'ContentDetails.LicensedContent') ? undefined : json['ContentDetails.LicensedContent'],
        'contentDetailsProjection': !exists(json, 'ContentDetails.Projection') ? undefined : json['ContentDetails.Projection'],
        'contentDetailsRegionRestrictionAllowed': !exists(json, 'ContentDetails.RegionRestriction.Allowed') ? undefined : json['ContentDetails.RegionRestriction.Allowed'],
        'contentDetailsRegionRestrictionBlocked': !exists(json, 'ContentDetails.RegionRestriction.Blocked') ? undefined : json['ContentDetails.RegionRestriction.Blocked'],
        'contentDetailsRegionRestrictionETag': !exists(json, 'ContentDetails.RegionRestriction.ETag') ? undefined : json['ContentDetails.RegionRestriction.ETag'],
        'contentDetailsETag': !exists(json, 'ContentDetails.ETag') ? undefined : json['ContentDetails.ETag'],
        'eTag': !exists(json, 'ETag') ? undefined : json['ETag'],
        'fileDetailsAudioStreams': !exists(json, 'FileDetails.AudioStreams') ? undefined : (json['FileDetails.AudioStreams'] === null ? null : (json['FileDetails.AudioStreams'] as Array<any>).map(VideoFileDetailsAudioStreamFromJSON)),
        'fileDetailsBitrateBps': !exists(json, 'FileDetails.BitrateBps') ? undefined : json['FileDetails.BitrateBps'],
        'fileDetailsContainer': !exists(json, 'FileDetails.Container') ? undefined : json['FileDetails.Container'],
        'fileDetailsCreationTime': !exists(json, 'FileDetails.CreationTime') ? undefined : json['FileDetails.CreationTime'],
        'fileDetailsDurationMs': !exists(json, 'FileDetails.DurationMs') ? undefined : json['FileDetails.DurationMs'],
        'fileDetailsFileName': !exists(json, 'FileDetails.FileName') ? undefined : json['FileDetails.FileName'],
        'fileDetailsFileSize': !exists(json, 'FileDetails.FileSize') ? undefined : json['FileDetails.FileSize'],
        'fileDetailsFileType': !exists(json, 'FileDetails.FileType') ? undefined : json['FileDetails.FileType'],
        'fileDetailsVideoStreams': !exists(json, 'FileDetails.VideoStreams') ? undefined : (json['FileDetails.VideoStreams'] === null ? null : (json['FileDetails.VideoStreams'] as Array<any>).map(VideoFileDetailsVideoStreamFromJSON)),
        'fileDetailsETag': !exists(json, 'FileDetails.ETag') ? undefined : json['FileDetails.ETag'],
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'kind': !exists(json, 'Kind') ? undefined : json['Kind'],
        'liveStreamingDetailsActiveLiveChatId': !exists(json, 'LiveStreamingDetails.ActiveLiveChatId') ? undefined : json['LiveStreamingDetails.ActiveLiveChatId'],
        'liveStreamingDetailsActualEndTimeRaw': !exists(json, 'LiveStreamingDetails.ActualEndTimeRaw') ? undefined : json['LiveStreamingDetails.ActualEndTimeRaw'],
        'liveStreamingDetailsActualEndTime': !exists(json, 'LiveStreamingDetails.ActualEndTime') ? undefined : (json['LiveStreamingDetails.ActualEndTime'] === null ? null : new Date(json['LiveStreamingDetails.ActualEndTime'])),
        'liveStreamingDetailsActualStartTimeRaw': !exists(json, 'LiveStreamingDetails.ActualStartTimeRaw') ? undefined : json['LiveStreamingDetails.ActualStartTimeRaw'],
        'liveStreamingDetailsActualStartTime': !exists(json, 'LiveStreamingDetails.ActualStartTime') ? undefined : (json['LiveStreamingDetails.ActualStartTime'] === null ? null : new Date(json['LiveStreamingDetails.ActualStartTime'])),
        'liveStreamingDetailsConcurrentViewers': !exists(json, 'LiveStreamingDetails.ConcurrentViewers') ? undefined : json['LiveStreamingDetails.ConcurrentViewers'],
        'liveStreamingDetailsScheduledEndTimeRaw': !exists(json, 'LiveStreamingDetails.ScheduledEndTimeRaw') ? undefined : json['LiveStreamingDetails.ScheduledEndTimeRaw'],
        'liveStreamingDetailsScheduledEndTime': !exists(json, 'LiveStreamingDetails.ScheduledEndTime') ? undefined : (json['LiveStreamingDetails.ScheduledEndTime'] === null ? null : new Date(json['LiveStreamingDetails.ScheduledEndTime'])),
        'liveStreamingDetailsScheduledStartTimeRaw': !exists(json, 'LiveStreamingDetails.ScheduledStartTimeRaw') ? undefined : json['LiveStreamingDetails.ScheduledStartTimeRaw'],
        'liveStreamingDetailsScheduledStartTime': !exists(json, 'LiveStreamingDetails.ScheduledStartTime') ? undefined : (json['LiveStreamingDetails.ScheduledStartTime'] === null ? null : new Date(json['LiveStreamingDetails.ScheduledStartTime'])),
        'liveStreamingDetailsETag': !exists(json, 'LiveStreamingDetails.ETag') ? undefined : json['LiveStreamingDetails.ETag'],
        'localizations': !exists(json, 'Localizations') ? undefined : (json['Localizations'] === null ? null : mapValues(json['Localizations'], VideoLocalizationFromJSON)),
        'monetizationDetailsAccessAllowed': !exists(json, 'MonetizationDetails.Access.Allowed') ? undefined : json['MonetizationDetails.Access.Allowed'],
        'monetizationDetailsAccessException': !exists(json, 'MonetizationDetails.Access.Exception') ? undefined : json['MonetizationDetails.Access.Exception'],
        'monetizationDetailsAccessETag': !exists(json, 'MonetizationDetails.Access.ETag') ? undefined : json['MonetizationDetails.Access.ETag'],
        'monetizationDetailsETag': !exists(json, 'MonetizationDetails.ETag') ? undefined : json['MonetizationDetails.ETag'],
        'playerEmbedHeight': !exists(json, 'Player.EmbedHeight') ? undefined : json['Player.EmbedHeight'],
        'playerEmbedHtml': !exists(json, 'Player.EmbedHtml') ? undefined : json['Player.EmbedHtml'],
        'playerEmbedWidth': !exists(json, 'Player.EmbedWidth') ? undefined : json['Player.EmbedWidth'],
        'playerETag': !exists(json, 'Player.ETag') ? undefined : json['Player.ETag'],
        'processingDetailsEditorSuggestionsAvailability': !exists(json, 'ProcessingDetails.EditorSuggestionsAvailability') ? undefined : json['ProcessingDetails.EditorSuggestionsAvailability'],
        'processingDetailsFileDetailsAvailability': !exists(json, 'ProcessingDetails.FileDetailsAvailability') ? undefined : json['ProcessingDetails.FileDetailsAvailability'],
        'processingDetailsProcessingFailureReason': !exists(json, 'ProcessingDetails.ProcessingFailureReason') ? undefined : json['ProcessingDetails.ProcessingFailureReason'],
        'processingDetailsProcessingIssuesAvailability': !exists(json, 'ProcessingDetails.ProcessingIssuesAvailability') ? undefined : json['ProcessingDetails.ProcessingIssuesAvailability'],
        'processingDetailsProcessingProgressPartsProcessed': !exists(json, 'ProcessingDetails.ProcessingProgress.PartsProcessed') ? undefined : json['ProcessingDetails.ProcessingProgress.PartsProcessed'],
        'processingDetailsProcessingProgressPartsTotal': !exists(json, 'ProcessingDetails.ProcessingProgress.PartsTotal') ? undefined : json['ProcessingDetails.ProcessingProgress.PartsTotal'],
        'processingDetailsProcessingProgressTimeLeftMs': !exists(json, 'ProcessingDetails.ProcessingProgress.TimeLeftMs') ? undefined : json['ProcessingDetails.ProcessingProgress.TimeLeftMs'],
        'processingDetailsProcessingProgressETag': !exists(json, 'ProcessingDetails.ProcessingProgress.ETag') ? undefined : json['ProcessingDetails.ProcessingProgress.ETag'],
        'processingDetailsProcessingStatus': !exists(json, 'ProcessingDetails.ProcessingStatus') ? undefined : json['ProcessingDetails.ProcessingStatus'],
        'processingDetailsTagSuggestionsAvailability': !exists(json, 'ProcessingDetails.TagSuggestionsAvailability') ? undefined : json['ProcessingDetails.TagSuggestionsAvailability'],
        'processingDetailsThumbnailsAvailability': !exists(json, 'ProcessingDetails.ThumbnailsAvailability') ? undefined : json['ProcessingDetails.ThumbnailsAvailability'],
        'processingDetailsETag': !exists(json, 'ProcessingDetails.ETag') ? undefined : json['ProcessingDetails.ETag'],
        'projectDetailsTags': !exists(json, 'ProjectDetails.Tags') ? undefined : json['ProjectDetails.Tags'],
        'projectDetailsETag': !exists(json, 'ProjectDetails.ETag') ? undefined : json['ProjectDetails.ETag'],
        'recordingDetailsLocationAltitude': !exists(json, 'RecordingDetails.Location.Altitude') ? undefined : json['RecordingDetails.Location.Altitude'],
        'recordingDetailsLocationLatitude': !exists(json, 'RecordingDetails.Location.Latitude') ? undefined : json['RecordingDetails.Location.Latitude'],
        'recordingDetailsLocationLongitude': !exists(json, 'RecordingDetails.Location.Longitude') ? undefined : json['RecordingDetails.Location.Longitude'],
        'recordingDetailsLocationETag': !exists(json, 'RecordingDetails.Location.ETag') ? undefined : json['RecordingDetails.Location.ETag'],
        'recordingDetailsLocationDescription': !exists(json, 'RecordingDetails.LocationDescription') ? undefined : json['RecordingDetails.LocationDescription'],
        'recordingDetailsRecordingDateRaw': !exists(json, 'RecordingDetails.RecordingDateRaw') ? undefined : json['RecordingDetails.RecordingDateRaw'],
        'recordingDetailsRecordingDate': !exists(json, 'RecordingDetails.RecordingDate') ? undefined : (json['RecordingDetails.RecordingDate'] === null ? null : new Date(json['RecordingDetails.RecordingDate'])),
        'recordingDetailsETag': !exists(json, 'RecordingDetails.ETag') ? undefined : json['RecordingDetails.ETag'],
        'snippetCategoryId': !exists(json, 'Snippet.CategoryId') ? undefined : json['Snippet.CategoryId'],
        'snippetChannelId': !exists(json, 'Snippet.ChannelId') ? undefined : json['Snippet.ChannelId'],
        'snippetChannelTitle': !exists(json, 'Snippet.ChannelTitle') ? undefined : json['Snippet.ChannelTitle'],
        'snippetDefaultAudioLanguage': !exists(json, 'Snippet.DefaultAudioLanguage') ? undefined : json['Snippet.DefaultAudioLanguage'],
        'snippetDefaultLanguage': !exists(json, 'Snippet.DefaultLanguage') ? undefined : json['Snippet.DefaultLanguage'],
        'snippetDescription': !exists(json, 'Snippet.Description') ? undefined : json['Snippet.Description'],
        'snippetLiveBroadcastContent': !exists(json, 'Snippet.LiveBroadcastContent') ? undefined : json['Snippet.LiveBroadcastContent'],
        'snippetLocalizedDescription': !exists(json, 'Snippet.Localized.Description') ? undefined : json['Snippet.Localized.Description'],
        'snippetLocalizedTitle': !exists(json, 'Snippet.Localized.Title') ? undefined : json['Snippet.Localized.Title'],
        'snippetLocalizedETag': !exists(json, 'Snippet.Localized.ETag') ? undefined : json['Snippet.Localized.ETag'],
        'snippetPublishedAtRaw': !exists(json, 'Snippet.PublishedAtRaw') ? undefined : json['Snippet.PublishedAtRaw'],
        'snippetPublishedAt': !exists(json, 'Snippet.PublishedAt') ? undefined : (json['Snippet.PublishedAt'] === null ? null : new Date(json['Snippet.PublishedAt'])),
        'snippetTags': !exists(json, 'Snippet.Tags') ? undefined : json['Snippet.Tags'],
        'snippetThumbnailsDefaultHeight': !exists(json, 'Snippet.Thumbnails.Default__.Height') ? undefined : json['Snippet.Thumbnails.Default__.Height'],
        'snippetThumbnailsDefaultUrl': !exists(json, 'Snippet.Thumbnails.Default__.Url') ? undefined : json['Snippet.Thumbnails.Default__.Url'],
        'snippetThumbnailsDefaultWidth': !exists(json, 'Snippet.Thumbnails.Default__.Width') ? undefined : json['Snippet.Thumbnails.Default__.Width'],
        'snippetThumbnailsDefaultETag': !exists(json, 'Snippet.Thumbnails.Default__.ETag') ? undefined : json['Snippet.Thumbnails.Default__.ETag'],
        'snippetThumbnailsHighHeight': !exists(json, 'Snippet.Thumbnails.High.Height') ? undefined : json['Snippet.Thumbnails.High.Height'],
        'snippetThumbnailsHighUrl': !exists(json, 'Snippet.Thumbnails.High.Url') ? undefined : json['Snippet.Thumbnails.High.Url'],
        'snippetThumbnailsHighWidth': !exists(json, 'Snippet.Thumbnails.High.Width') ? undefined : json['Snippet.Thumbnails.High.Width'],
        'snippetThumbnailsHighETag': !exists(json, 'Snippet.Thumbnails.High.ETag') ? undefined : json['Snippet.Thumbnails.High.ETag'],
        'snippetThumbnailsMaxresHeight': !exists(json, 'Snippet.Thumbnails.Maxres.Height') ? undefined : json['Snippet.Thumbnails.Maxres.Height'],
        'snippetThumbnailsMaxresUrl': !exists(json, 'Snippet.Thumbnails.Maxres.Url') ? undefined : json['Snippet.Thumbnails.Maxres.Url'],
        'snippetThumbnailsMaxresWidth': !exists(json, 'Snippet.Thumbnails.Maxres.Width') ? undefined : json['Snippet.Thumbnails.Maxres.Width'],
        'snippetThumbnailsMaxresETag': !exists(json, 'Snippet.Thumbnails.Maxres.ETag') ? undefined : json['Snippet.Thumbnails.Maxres.ETag'],
        'snippetThumbnailsMediumHeight': !exists(json, 'Snippet.Thumbnails.Medium.Height') ? undefined : json['Snippet.Thumbnails.Medium.Height'],
        'snippetThumbnailsMediumUrl': !exists(json, 'Snippet.Thumbnails.Medium.Url') ? undefined : json['Snippet.Thumbnails.Medium.Url'],
        'snippetThumbnailsMediumWidth': !exists(json, 'Snippet.Thumbnails.Medium.Width') ? undefined : json['Snippet.Thumbnails.Medium.Width'],
        'snippetThumbnailsMediumETag': !exists(json, 'Snippet.Thumbnails.Medium.ETag') ? undefined : json['Snippet.Thumbnails.Medium.ETag'],
        'snippetThumbnailsStandardHeight': !exists(json, 'Snippet.Thumbnails.Standard.Height') ? undefined : json['Snippet.Thumbnails.Standard.Height'],
        'snippetThumbnailsStandardUrl': !exists(json, 'Snippet.Thumbnails.Standard.Url') ? undefined : json['Snippet.Thumbnails.Standard.Url'],
        'snippetThumbnailsStandardWidth': !exists(json, 'Snippet.Thumbnails.Standard.Width') ? undefined : json['Snippet.Thumbnails.Standard.Width'],
        'snippetThumbnailsStandardETag': !exists(json, 'Snippet.Thumbnails.Standard.ETag') ? undefined : json['Snippet.Thumbnails.Standard.ETag'],
        'snippetThumbnailsETag': !exists(json, 'Snippet.Thumbnails.ETag') ? undefined : json['Snippet.Thumbnails.ETag'],
        'snippetTitle': !exists(json, 'Snippet.Title') ? undefined : json['Snippet.Title'],
        'snippetETag': !exists(json, 'Snippet.ETag') ? undefined : json['Snippet.ETag'],
        'statisticsCommentCount': !exists(json, 'Statistics.CommentCount') ? undefined : json['Statistics.CommentCount'],
        'statisticsDislikeCount': !exists(json, 'Statistics.DislikeCount') ? undefined : json['Statistics.DislikeCount'],
        'statisticsFavoriteCount': !exists(json, 'Statistics.FavoriteCount') ? undefined : json['Statistics.FavoriteCount'],
        'statisticsLikeCount': !exists(json, 'Statistics.LikeCount') ? undefined : json['Statistics.LikeCount'],
        'statisticsViewCount': !exists(json, 'Statistics.ViewCount') ? undefined : json['Statistics.ViewCount'],
        'statisticsETag': !exists(json, 'Statistics.ETag') ? undefined : json['Statistics.ETag'],
        'statusEmbeddable': !exists(json, 'Status.Embeddable') ? undefined : json['Status.Embeddable'],
        'statusFailureReason': !exists(json, 'Status.FailureReason') ? undefined : json['Status.FailureReason'],
        'statusLicense': !exists(json, 'Status.License') ? undefined : json['Status.License'],
        'statusMadeForKids': !exists(json, 'Status.MadeForKids') ? undefined : json['Status.MadeForKids'],
        'statusPrivacyStatus': !exists(json, 'Status.PrivacyStatus') ? undefined : json['Status.PrivacyStatus'],
        'statusPublicStatsViewable': !exists(json, 'Status.PublicStatsViewable') ? undefined : json['Status.PublicStatsViewable'],
        'statusPublishAtRaw': !exists(json, 'Status.PublishAtRaw') ? undefined : json['Status.PublishAtRaw'],
        'statusPublishAt': !exists(json, 'Status.PublishAt') ? undefined : (json['Status.PublishAt'] === null ? null : new Date(json['Status.PublishAt'])),
        'statusRejectionReason': !exists(json, 'Status.RejectionReason') ? undefined : json['Status.RejectionReason'],
        'statusSelfDeclaredMadeForKids': !exists(json, 'Status.SelfDeclaredMadeForKids') ? undefined : json['Status.SelfDeclaredMadeForKids'],
        'statusUploadStatus': !exists(json, 'Status.UploadStatus') ? undefined : json['Status.UploadStatus'],
        'statusETag': !exists(json, 'Status.ETag') ? undefined : json['Status.ETag'],
        'suggestionsEditorSuggestions': !exists(json, 'Suggestions.EditorSuggestions') ? undefined : json['Suggestions.EditorSuggestions'],
        'suggestionsProcessingErrors': !exists(json, 'Suggestions.ProcessingErrors') ? undefined : json['Suggestions.ProcessingErrors'],
        'suggestionsProcessingHints': !exists(json, 'Suggestions.ProcessingHints') ? undefined : json['Suggestions.ProcessingHints'],
        'suggestionsProcessingWarnings': !exists(json, 'Suggestions.ProcessingWarnings') ? undefined : json['Suggestions.ProcessingWarnings'],
        'suggestionsTagSuggestions': !exists(json, 'Suggestions.TagSuggestions') ? undefined : (json['Suggestions.TagSuggestions'] === null ? null : (json['Suggestions.TagSuggestions'] as Array<any>).map(VideoSuggestionsTagSuggestionFromJSON)),
        'suggestionsETag': !exists(json, 'Suggestions.ETag') ? undefined : json['Suggestions.ETag'],
        'topicDetailsRelevantTopicIds': !exists(json, 'TopicDetails.RelevantTopicIds') ? undefined : json['TopicDetails.RelevantTopicIds'],
        'topicDetailsTopicCategories': !exists(json, 'TopicDetails.TopicCategories') ? undefined : json['TopicDetails.TopicCategories'],
        'topicDetailsTopicIds': !exists(json, 'TopicDetails.TopicIds') ? undefined : json['TopicDetails.TopicIds'],
        'topicDetailsETag': !exists(json, 'TopicDetails.ETag') ? undefined : json['TopicDetails.ETag'],
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AgeGating.AlcoholContent': value.ageGatingAlcoholContent,
        'AgeGating.Restricted': value.ageGatingRestricted,
        'AgeGating.VideoGameRating': value.ageGatingVideoGameRating,
        'AgeGating.ETag': value.ageGatingETag,
        'ContentDetails.Caption': value.contentDetailsCaption,
        'ContentDetails.ContentRating.AcbRating': value.contentDetailsContentRatingAcbRating,
        'ContentDetails.ContentRating.AgcomRating': value.contentDetailsContentRatingAgcomRating,
        'ContentDetails.ContentRating.AnatelRating': value.contentDetailsContentRatingAnatelRating,
        'ContentDetails.ContentRating.BbfcRating': value.contentDetailsContentRatingBbfcRating,
        'ContentDetails.ContentRating.BfvcRating': value.contentDetailsContentRatingBfvcRating,
        'ContentDetails.ContentRating.BmukkRating': value.contentDetailsContentRatingBmukkRating,
        'ContentDetails.ContentRating.CatvRating': value.contentDetailsContentRatingCatvRating,
        'ContentDetails.ContentRating.CatvfrRating': value.contentDetailsContentRatingCatvfrRating,
        'ContentDetails.ContentRating.CbfcRating': value.contentDetailsContentRatingCbfcRating,
        'ContentDetails.ContentRating.CccRating': value.contentDetailsContentRatingCccRating,
        'ContentDetails.ContentRating.CceRating': value.contentDetailsContentRatingCceRating,
        'ContentDetails.ContentRating.ChfilmRating': value.contentDetailsContentRatingChfilmRating,
        'ContentDetails.ContentRating.ChvrsRating': value.contentDetailsContentRatingChvrsRating,
        'ContentDetails.ContentRating.CicfRating': value.contentDetailsContentRatingCicfRating,
        'ContentDetails.ContentRating.CnaRating': value.contentDetailsContentRatingCnaRating,
        'ContentDetails.ContentRating.CncRating': value.contentDetailsContentRatingCncRating,
        'ContentDetails.ContentRating.CsaRating': value.contentDetailsContentRatingCsaRating,
        'ContentDetails.ContentRating.CscfRating': value.contentDetailsContentRatingCscfRating,
        'ContentDetails.ContentRating.CzfilmRating': value.contentDetailsContentRatingCzfilmRating,
        'ContentDetails.ContentRating.DjctqRating': value.contentDetailsContentRatingDjctqRating,
        'ContentDetails.ContentRating.DjctqRatingReasons': value.contentDetailsContentRatingDjctqRatingReasons,
        'ContentDetails.ContentRating.EcbmctRating': value.contentDetailsContentRatingEcbmctRating,
        'ContentDetails.ContentRating.EefilmRating': value.contentDetailsContentRatingEefilmRating,
        'ContentDetails.ContentRating.EgfilmRating': value.contentDetailsContentRatingEgfilmRating,
        'ContentDetails.ContentRating.EirinRating': value.contentDetailsContentRatingEirinRating,
        'ContentDetails.ContentRating.FcbmRating': value.contentDetailsContentRatingFcbmRating,
        'ContentDetails.ContentRating.FcoRating': value.contentDetailsContentRatingFcoRating,
        'ContentDetails.ContentRating.FmocRating': value.contentDetailsContentRatingFmocRating,
        'ContentDetails.ContentRating.FpbRating': value.contentDetailsContentRatingFpbRating,
        'ContentDetails.ContentRating.FpbRatingReasons': value.contentDetailsContentRatingFpbRatingReasons,
        'ContentDetails.ContentRating.FskRating': value.contentDetailsContentRatingFskRating,
        'ContentDetails.ContentRating.GrfilmRating': value.contentDetailsContentRatingGrfilmRating,
        'ContentDetails.ContentRating.IcaaRating': value.contentDetailsContentRatingIcaaRating,
        'ContentDetails.ContentRating.IfcoRating': value.contentDetailsContentRatingIfcoRating,
        'ContentDetails.ContentRating.IlfilmRating': value.contentDetailsContentRatingIlfilmRating,
        'ContentDetails.ContentRating.IncaaRating': value.contentDetailsContentRatingIncaaRating,
        'ContentDetails.ContentRating.KfcbRating': value.contentDetailsContentRatingKfcbRating,
        'ContentDetails.ContentRating.KijkwijzerRating': value.contentDetailsContentRatingKijkwijzerRating,
        'ContentDetails.ContentRating.KmrbRating': value.contentDetailsContentRatingKmrbRating,
        'ContentDetails.ContentRating.LsfRating': value.contentDetailsContentRatingLsfRating,
        'ContentDetails.ContentRating.MccaaRating': value.contentDetailsContentRatingMccaaRating,
        'ContentDetails.ContentRating.MccypRating': value.contentDetailsContentRatingMccypRating,
        'ContentDetails.ContentRating.McstRating': value.contentDetailsContentRatingMcstRating,
        'ContentDetails.ContentRating.MdaRating': value.contentDetailsContentRatingMdaRating,
        'ContentDetails.ContentRating.MedietilsynetRating': value.contentDetailsContentRatingMedietilsynetRating,
        'ContentDetails.ContentRating.MekuRating': value.contentDetailsContentRatingMekuRating,
        'ContentDetails.ContentRating.MenaMpaaRating': value.contentDetailsContentRatingMenaMpaaRating,
        'ContentDetails.ContentRating.MibacRating': value.contentDetailsContentRatingMibacRating,
        'ContentDetails.ContentRating.MocRating': value.contentDetailsContentRatingMocRating,
        'ContentDetails.ContentRating.MoctwRating': value.contentDetailsContentRatingMoctwRating,
        'ContentDetails.ContentRating.MpaaRating': value.contentDetailsContentRatingMpaaRating,
        'ContentDetails.ContentRating.MpaatRating': value.contentDetailsContentRatingMpaatRating,
        'ContentDetails.ContentRating.MtrcbRating': value.contentDetailsContentRatingMtrcbRating,
        'ContentDetails.ContentRating.NbcRating': value.contentDetailsContentRatingNbcRating,
        'ContentDetails.ContentRating.NbcplRating': value.contentDetailsContentRatingNbcplRating,
        'ContentDetails.ContentRating.NfrcRating': value.contentDetailsContentRatingNfrcRating,
        'ContentDetails.ContentRating.NfvcbRating': value.contentDetailsContentRatingNfvcbRating,
        'ContentDetails.ContentRating.NkclvRating': value.contentDetailsContentRatingNkclvRating,
        'ContentDetails.ContentRating.NmcRating': value.contentDetailsContentRatingNmcRating,
        'ContentDetails.ContentRating.OflcRating': value.contentDetailsContentRatingOflcRating,
        'ContentDetails.ContentRating.PefilmRating': value.contentDetailsContentRatingPefilmRating,
        'ContentDetails.ContentRating.RcnofRating': value.contentDetailsContentRatingRcnofRating,
        'ContentDetails.ContentRating.ResorteviolenciaRating': value.contentDetailsContentRatingResorteviolenciaRating,
        'ContentDetails.ContentRating.RtcRating': value.contentDetailsContentRatingRtcRating,
        'ContentDetails.ContentRating.RteRating': value.contentDetailsContentRatingRteRating,
        'ContentDetails.ContentRating.RussiaRating': value.contentDetailsContentRatingRussiaRating,
        'ContentDetails.ContentRating.SkfilmRating': value.contentDetailsContentRatingSkfilmRating,
        'ContentDetails.ContentRating.SmaisRating': value.contentDetailsContentRatingSmaisRating,
        'ContentDetails.ContentRating.SmsaRating': value.contentDetailsContentRatingSmsaRating,
        'ContentDetails.ContentRating.TvpgRating': value.contentDetailsContentRatingTvpgRating,
        'ContentDetails.ContentRating.YtRating': value.contentDetailsContentRatingYtRating,
        'ContentDetails.ContentRating.ETag': value.contentDetailsContentRatingETag,
        'ContentDetails.CountryRestriction.Allowed': value.contentDetailsCountryRestrictionAllowed,
        'ContentDetails.CountryRestriction.Exception': value.contentDetailsCountryRestrictionException,
        'ContentDetails.CountryRestriction.ETag': value.contentDetailsCountryRestrictionETag,
        'ContentDetails.Definition': value.contentDetailsDefinition,
        'ContentDetails.Dimension': value.contentDetailsDimension,
        'ContentDetails.Duration': value.contentDetailsDuration,
        'ContentDetails.HasCustomThumbnail': value.contentDetailsHasCustomThumbnail,
        'ContentDetails.LicensedContent': value.contentDetailsLicensedContent,
        'ContentDetails.Projection': value.contentDetailsProjection,
        'ContentDetails.RegionRestriction.Allowed': value.contentDetailsRegionRestrictionAllowed,
        'ContentDetails.RegionRestriction.Blocked': value.contentDetailsRegionRestrictionBlocked,
        'ContentDetails.RegionRestriction.ETag': value.contentDetailsRegionRestrictionETag,
        'ContentDetails.ETag': value.contentDetailsETag,
        'ETag': value.eTag,
        'FileDetails.AudioStreams': value.fileDetailsAudioStreams === undefined ? undefined : (value.fileDetailsAudioStreams === null ? null : (value.fileDetailsAudioStreams as Array<any>).map(VideoFileDetailsAudioStreamToJSON)),
        'FileDetails.BitrateBps': value.fileDetailsBitrateBps,
        'FileDetails.Container': value.fileDetailsContainer,
        'FileDetails.CreationTime': value.fileDetailsCreationTime,
        'FileDetails.DurationMs': value.fileDetailsDurationMs,
        'FileDetails.FileName': value.fileDetailsFileName,
        'FileDetails.FileSize': value.fileDetailsFileSize,
        'FileDetails.FileType': value.fileDetailsFileType,
        'FileDetails.VideoStreams': value.fileDetailsVideoStreams === undefined ? undefined : (value.fileDetailsVideoStreams === null ? null : (value.fileDetailsVideoStreams as Array<any>).map(VideoFileDetailsVideoStreamToJSON)),
        'FileDetails.ETag': value.fileDetailsETag,
        'Id': value.id,
        'Kind': value.kind,
        'LiveStreamingDetails.ActiveLiveChatId': value.liveStreamingDetailsActiveLiveChatId,
        'LiveStreamingDetails.ActualEndTimeRaw': value.liveStreamingDetailsActualEndTimeRaw,
        'LiveStreamingDetails.ActualEndTime': value.liveStreamingDetailsActualEndTime === undefined ? undefined : (value.liveStreamingDetailsActualEndTime === null ? null : value.liveStreamingDetailsActualEndTime.toISOString()),
        'LiveStreamingDetails.ActualStartTimeRaw': value.liveStreamingDetailsActualStartTimeRaw,
        'LiveStreamingDetails.ActualStartTime': value.liveStreamingDetailsActualStartTime === undefined ? undefined : (value.liveStreamingDetailsActualStartTime === null ? null : value.liveStreamingDetailsActualStartTime.toISOString()),
        'LiveStreamingDetails.ConcurrentViewers': value.liveStreamingDetailsConcurrentViewers,
        'LiveStreamingDetails.ScheduledEndTimeRaw': value.liveStreamingDetailsScheduledEndTimeRaw,
        'LiveStreamingDetails.ScheduledEndTime': value.liveStreamingDetailsScheduledEndTime === undefined ? undefined : (value.liveStreamingDetailsScheduledEndTime === null ? null : value.liveStreamingDetailsScheduledEndTime.toISOString()),
        'LiveStreamingDetails.ScheduledStartTimeRaw': value.liveStreamingDetailsScheduledStartTimeRaw,
        'LiveStreamingDetails.ScheduledStartTime': value.liveStreamingDetailsScheduledStartTime === undefined ? undefined : (value.liveStreamingDetailsScheduledStartTime === null ? null : value.liveStreamingDetailsScheduledStartTime.toISOString()),
        'LiveStreamingDetails.ETag': value.liveStreamingDetailsETag,
        'Localizations': value.localizations === undefined ? undefined : (value.localizations === null ? null : mapValues(value.localizations, VideoLocalizationToJSON)),
        'MonetizationDetails.Access.Allowed': value.monetizationDetailsAccessAllowed,
        'MonetizationDetails.Access.Exception': value.monetizationDetailsAccessException,
        'MonetizationDetails.Access.ETag': value.monetizationDetailsAccessETag,
        'MonetizationDetails.ETag': value.monetizationDetailsETag,
        'Player.EmbedHeight': value.playerEmbedHeight,
        'Player.EmbedHtml': value.playerEmbedHtml,
        'Player.EmbedWidth': value.playerEmbedWidth,
        'Player.ETag': value.playerETag,
        'ProcessingDetails.EditorSuggestionsAvailability': value.processingDetailsEditorSuggestionsAvailability,
        'ProcessingDetails.FileDetailsAvailability': value.processingDetailsFileDetailsAvailability,
        'ProcessingDetails.ProcessingFailureReason': value.processingDetailsProcessingFailureReason,
        'ProcessingDetails.ProcessingIssuesAvailability': value.processingDetailsProcessingIssuesAvailability,
        'ProcessingDetails.ProcessingProgress.PartsProcessed': value.processingDetailsProcessingProgressPartsProcessed,
        'ProcessingDetails.ProcessingProgress.PartsTotal': value.processingDetailsProcessingProgressPartsTotal,
        'ProcessingDetails.ProcessingProgress.TimeLeftMs': value.processingDetailsProcessingProgressTimeLeftMs,
        'ProcessingDetails.ProcessingProgress.ETag': value.processingDetailsProcessingProgressETag,
        'ProcessingDetails.ProcessingStatus': value.processingDetailsProcessingStatus,
        'ProcessingDetails.TagSuggestionsAvailability': value.processingDetailsTagSuggestionsAvailability,
        'ProcessingDetails.ThumbnailsAvailability': value.processingDetailsThumbnailsAvailability,
        'ProcessingDetails.ETag': value.processingDetailsETag,
        'ProjectDetails.Tags': value.projectDetailsTags,
        'ProjectDetails.ETag': value.projectDetailsETag,
        'RecordingDetails.Location.Altitude': value.recordingDetailsLocationAltitude,
        'RecordingDetails.Location.Latitude': value.recordingDetailsLocationLatitude,
        'RecordingDetails.Location.Longitude': value.recordingDetailsLocationLongitude,
        'RecordingDetails.Location.ETag': value.recordingDetailsLocationETag,
        'RecordingDetails.LocationDescription': value.recordingDetailsLocationDescription,
        'RecordingDetails.RecordingDateRaw': value.recordingDetailsRecordingDateRaw,
        'RecordingDetails.RecordingDate': value.recordingDetailsRecordingDate === undefined ? undefined : (value.recordingDetailsRecordingDate === null ? null : value.recordingDetailsRecordingDate.toISOString()),
        'RecordingDetails.ETag': value.recordingDetailsETag,
        'Snippet.CategoryId': value.snippetCategoryId,
        'Snippet.ChannelId': value.snippetChannelId,
        'Snippet.ChannelTitle': value.snippetChannelTitle,
        'Snippet.DefaultAudioLanguage': value.snippetDefaultAudioLanguage,
        'Snippet.DefaultLanguage': value.snippetDefaultLanguage,
        'Snippet.Description': value.snippetDescription,
        'Snippet.LiveBroadcastContent': value.snippetLiveBroadcastContent,
        'Snippet.Localized.Description': value.snippetLocalizedDescription,
        'Snippet.Localized.Title': value.snippetLocalizedTitle,
        'Snippet.Localized.ETag': value.snippetLocalizedETag,
        'Snippet.PublishedAtRaw': value.snippetPublishedAtRaw,
        'Snippet.PublishedAt': value.snippetPublishedAt === undefined ? undefined : (value.snippetPublishedAt === null ? null : value.snippetPublishedAt.toISOString()),
        'Snippet.Tags': value.snippetTags,
        'Snippet.Thumbnails.Default__.Height': value.snippetThumbnailsDefaultHeight,
        'Snippet.Thumbnails.Default__.Url': value.snippetThumbnailsDefaultUrl,
        'Snippet.Thumbnails.Default__.Width': value.snippetThumbnailsDefaultWidth,
        'Snippet.Thumbnails.Default__.ETag': value.snippetThumbnailsDefaultETag,
        'Snippet.Thumbnails.High.Height': value.snippetThumbnailsHighHeight,
        'Snippet.Thumbnails.High.Url': value.snippetThumbnailsHighUrl,
        'Snippet.Thumbnails.High.Width': value.snippetThumbnailsHighWidth,
        'Snippet.Thumbnails.High.ETag': value.snippetThumbnailsHighETag,
        'Snippet.Thumbnails.Maxres.Height': value.snippetThumbnailsMaxresHeight,
        'Snippet.Thumbnails.Maxres.Url': value.snippetThumbnailsMaxresUrl,
        'Snippet.Thumbnails.Maxres.Width': value.snippetThumbnailsMaxresWidth,
        'Snippet.Thumbnails.Maxres.ETag': value.snippetThumbnailsMaxresETag,
        'Snippet.Thumbnails.Medium.Height': value.snippetThumbnailsMediumHeight,
        'Snippet.Thumbnails.Medium.Url': value.snippetThumbnailsMediumUrl,
        'Snippet.Thumbnails.Medium.Width': value.snippetThumbnailsMediumWidth,
        'Snippet.Thumbnails.Medium.ETag': value.snippetThumbnailsMediumETag,
        'Snippet.Thumbnails.Standard.Height': value.snippetThumbnailsStandardHeight,
        'Snippet.Thumbnails.Standard.Url': value.snippetThumbnailsStandardUrl,
        'Snippet.Thumbnails.Standard.Width': value.snippetThumbnailsStandardWidth,
        'Snippet.Thumbnails.Standard.ETag': value.snippetThumbnailsStandardETag,
        'Snippet.Thumbnails.ETag': value.snippetThumbnailsETag,
        'Snippet.Title': value.snippetTitle,
        'Snippet.ETag': value.snippetETag,
        'Statistics.CommentCount': value.statisticsCommentCount,
        'Statistics.DislikeCount': value.statisticsDislikeCount,
        'Statistics.FavoriteCount': value.statisticsFavoriteCount,
        'Statistics.LikeCount': value.statisticsLikeCount,
        'Statistics.ViewCount': value.statisticsViewCount,
        'Statistics.ETag': value.statisticsETag,
        'Status.Embeddable': value.statusEmbeddable,
        'Status.FailureReason': value.statusFailureReason,
        'Status.License': value.statusLicense,
        'Status.MadeForKids': value.statusMadeForKids,
        'Status.PrivacyStatus': value.statusPrivacyStatus,
        'Status.PublicStatsViewable': value.statusPublicStatsViewable,
        'Status.PublishAtRaw': value.statusPublishAtRaw,
        'Status.PublishAt': value.statusPublishAt === undefined ? undefined : (value.statusPublishAt === null ? null : value.statusPublishAt.toISOString()),
        'Status.RejectionReason': value.statusRejectionReason,
        'Status.SelfDeclaredMadeForKids': value.statusSelfDeclaredMadeForKids,
        'Status.UploadStatus': value.statusUploadStatus,
        'Status.ETag': value.statusETag,
        'Suggestions.EditorSuggestions': value.suggestionsEditorSuggestions,
        'Suggestions.ProcessingErrors': value.suggestionsProcessingErrors,
        'Suggestions.ProcessingHints': value.suggestionsProcessingHints,
        'Suggestions.ProcessingWarnings': value.suggestionsProcessingWarnings,
        'Suggestions.TagSuggestions': value.suggestionsTagSuggestions === undefined ? undefined : (value.suggestionsTagSuggestions === null ? null : (value.suggestionsTagSuggestions as Array<any>).map(VideoSuggestionsTagSuggestionToJSON)),
        'Suggestions.ETag': value.suggestionsETag,
        'TopicDetails.RelevantTopicIds': value.topicDetailsRelevantTopicIds,
        'TopicDetails.TopicCategories': value.topicDetailsTopicCategories,
        'TopicDetails.TopicIds': value.topicDetailsTopicIds,
        'TopicDetails.ETag': value.topicDetailsETag,
    };
}


