/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InvideoPosition,
    InvideoPositionFromJSON,
    InvideoPositionFromJSONTyped,
    InvideoPositionToJSON,
    InvideoTiming,
    InvideoTimingFromJSON,
    InvideoTimingFromJSONTyped,
    InvideoTimingToJSON,
    PromotedItem,
    PromotedItemFromJSON,
    PromotedItemFromJSONTyped,
    PromotedItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface InvideoPromotion
 */
export interface InvideoPromotion {
    /**
     * 
     * @type {InvideoTiming}
     * @memberof InvideoPromotion
     */
    defaultTiming?: InvideoTiming;
    /**
     * 
     * @type {Array<PromotedItem>}
     * @memberof InvideoPromotion
     */
    items?: Array<PromotedItem> | null;
    /**
     * 
     * @type {InvideoPosition}
     * @memberof InvideoPromotion
     */
    position?: InvideoPosition;
    /**
     * 
     * @type {boolean}
     * @memberof InvideoPromotion
     */
    useSmartTiming?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof InvideoPromotion
     */
    eTag?: string | null;
}

export function InvideoPromotionFromJSON(json: any): InvideoPromotion {
    return InvideoPromotionFromJSONTyped(json, false);
}

export function InvideoPromotionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvideoPromotion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultTiming': !exists(json, 'defaultTiming') ? undefined : InvideoTimingFromJSON(json['defaultTiming']),
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(PromotedItemFromJSON)),
        'position': !exists(json, 'position') ? undefined : InvideoPositionFromJSON(json['position']),
        'useSmartTiming': !exists(json, 'useSmartTiming') ? undefined : json['useSmartTiming'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function InvideoPromotionToJSON(value?: InvideoPromotion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaultTiming': InvideoTimingToJSON(value.defaultTiming),
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(PromotedItemToJSON)),
        'position': InvideoPositionToJSON(value.position),
        'useSmartTiming': value.useSmartTiming,
        'eTag': value.eTag,
    };
}


