/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvideoTiming
 */
export interface InvideoTiming {
    /**
     * 
     * @type {number}
     * @memberof InvideoTiming
     */
    durationMs?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InvideoTiming
     */
    offsetMs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InvideoTiming
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvideoTiming
     */
    eTag?: string | null;
}

export function InvideoTimingFromJSON(json: any): InvideoTiming {
    return InvideoTimingFromJSONTyped(json, false);
}

export function InvideoTimingFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvideoTiming {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'durationMs': !exists(json, 'durationMs') ? undefined : json['durationMs'],
        'offsetMs': !exists(json, 'offsetMs') ? undefined : json['offsetMs'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function InvideoTimingToJSON(value?: InvideoTiming | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'durationMs': value.durationMs,
        'offsetMs': value.offsetMs,
        'type': value.type,
        'eTag': value.eTag,
    };
}


