/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalizedString
 */
export interface LocalizedString {
    /**
     * 
     * @type {string}
     * @memberof LocalizedString
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocalizedString
     */
    value?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocalizedString
     */
    eTag?: string | null;
}

export function LocalizedStringFromJSON(json: any): LocalizedString {
    return LocalizedStringFromJSONTyped(json, false);
}

export function LocalizedStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'language': !exists(json, 'language') ? undefined : json['language'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function LocalizedStringToJSON(value?: LocalizedString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'language': value.language,
        'value': value.value,
        'eTag': value.eTag,
    };
}


