/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    resultsPerPage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    totalResults?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PageInfo
     */
    eTag?: string | null;
}

export function PageInfoFromJSON(json: any): PageInfo {
    return PageInfoFromJSONTyped(json, false);
}

export function PageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resultsPerPage': !exists(json, 'resultsPerPage') ? undefined : json['resultsPerPage'],
        'totalResults': !exists(json, 'totalResults') ? undefined : json['totalResults'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function PageInfoToJSON(value?: PageInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resultsPerPage': value.resultsPerPage,
        'totalResults': value.totalResults,
        'eTag': value.eTag,
    };
}


