/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaylistItemStatus
 */
export interface PlaylistItemStatus {
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemStatus
     */
    privacyStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemStatus
     */
    eTag?: string | null;
}

export function PlaylistItemStatusFromJSON(json: any): PlaylistItemStatus {
    return PlaylistItemStatusFromJSONTyped(json, false);
}

export function PlaylistItemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistItemStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'privacyStatus': !exists(json, 'privacyStatus') ? undefined : json['privacyStatus'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function PlaylistItemStatusToJSON(value?: PlaylistItemStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'privacyStatus': value.privacyStatus,
        'eTag': value.eTag,
    };
}


