/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromotedItemId
 */
export interface PromotedItemId {
    /**
     * 
     * @type {string}
     * @memberof PromotedItemId
     */
    recentlyUploadedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PromotedItemId
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PromotedItemId
     */
    videoId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PromotedItemId
     */
    websiteUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PromotedItemId
     */
    eTag?: string | null;
}

export function PromotedItemIdFromJSON(json: any): PromotedItemId {
    return PromotedItemIdFromJSONTyped(json, false);
}

export function PromotedItemIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotedItemId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recentlyUploadedBy': !exists(json, 'recentlyUploadedBy') ? undefined : json['recentlyUploadedBy'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'videoId': !exists(json, 'videoId') ? undefined : json['videoId'],
        'websiteUrl': !exists(json, 'websiteUrl') ? undefined : json['websiteUrl'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function PromotedItemIdToJSON(value?: PromotedItemId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recentlyUploadedBy': value.recentlyUploadedBy,
        'type': value.type,
        'videoId': value.videoId,
        'websiteUrl': value.websiteUrl,
        'eTag': value.eTag,
    };
}


