/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InvideoTiming,
    InvideoTimingFromJSON,
    InvideoTimingFromJSONTyped,
    InvideoTimingToJSON,
    PromotedItemId,
    PromotedItemIdFromJSON,
    PromotedItemIdFromJSONTyped,
    PromotedItemIdToJSON,
} from './';

/**
 * 
 * @export
 * @interface PromotedItem
 */
export interface PromotedItem {
    /**
     * 
     * @type {string}
     * @memberof PromotedItem
     */
    customMessage?: string | null;
    /**
     * 
     * @type {PromotedItemId}
     * @memberof PromotedItem
     */
    id?: PromotedItemId;
    /**
     * 
     * @type {boolean}
     * @memberof PromotedItem
     */
    promotedByContentOwner?: boolean | null;
    /**
     * 
     * @type {InvideoTiming}
     * @memberof PromotedItem
     */
    timing?: InvideoTiming;
    /**
     * 
     * @type {string}
     * @memberof PromotedItem
     */
    eTag?: string | null;
}

export function PromotedItemFromJSON(json: any): PromotedItem {
    return PromotedItemFromJSONTyped(json, false);
}

export function PromotedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotedItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customMessage': !exists(json, 'customMessage') ? undefined : json['customMessage'],
        'id': !exists(json, 'id') ? undefined : PromotedItemIdFromJSON(json['id']),
        'promotedByContentOwner': !exists(json, 'promotedByContentOwner') ? undefined : json['promotedByContentOwner'],
        'timing': !exists(json, 'timing') ? undefined : InvideoTimingFromJSON(json['timing']),
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function PromotedItemToJSON(value?: PromotedItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customMessage': value.customMessage,
        'id': PromotedItemIdToJSON(value.id),
        'promotedByContentOwner': value.promotedByContentOwner,
        'timing': InvideoTimingToJSON(value.timing),
        'eTag': value.eTag,
    };
}


