/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyValue
 */
export interface PropertyValue {
    /**
     * 
     * @type {string}
     * @memberof PropertyValue
     */
    property?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyValue
     */
    value?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyValue
     */
    eTag?: string | null;
}

export function PropertyValueFromJSON(json: any): PropertyValue {
    return PropertyValueFromJSONTyped(json, false);
}

export function PropertyValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'property': !exists(json, 'property') ? undefined : json['property'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function PropertyValueToJSON(value?: PropertyValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'property': value.property,
        'value': value.value,
        'eTag': value.eTag,
    };
}


