/* tslint:disable */
/* eslint-disable */
/**
 * Meta Localize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SupportedLanguage
 */
export interface SupportedLanguage {
    /**
     * 
     * @type {string}
     * @memberof SupportedLanguage
     */
    languageCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupportedLanguage
     */
    displayName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SupportedLanguage
     */
    supportSource?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SupportedLanguage
     */
    supportTarget?: boolean;
}

export function SupportedLanguageFromJSON(json: any): SupportedLanguage {
    return SupportedLanguageFromJSONTyped(json, false);
}

export function SupportedLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportedLanguage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'languageCode': !exists(json, 'languageCode') ? undefined : json['languageCode'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'supportSource': !exists(json, 'supportSource') ? undefined : json['supportSource'],
        'supportTarget': !exists(json, 'supportTarget') ? undefined : json['supportTarget'],
    };
}

export function SupportedLanguageToJSON(value?: SupportedLanguage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'languageCode': value.languageCode,
        'displayName': value.displayName,
        'supportSource': value.supportSource,
        'supportTarget': value.supportTarget,
    };
}


