/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Thumbnail,
    ThumbnailFromJSON,
    ThumbnailFromJSONTyped,
    ThumbnailToJSON,
} from './';

/**
 * 
 * @export
 * @interface ThumbnailDetails
 */
export interface ThumbnailDetails {
    /**
     * 
     * @type {Thumbnail}
     * @memberof ThumbnailDetails
     */
    _default?: Thumbnail;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ThumbnailDetails
     */
    high?: Thumbnail;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ThumbnailDetails
     */
    maxres?: Thumbnail;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ThumbnailDetails
     */
    medium?: Thumbnail;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ThumbnailDetails
     */
    standard?: Thumbnail;
    /**
     * 
     * @type {string}
     * @memberof ThumbnailDetails
     */
    eTag?: string | null;
}

export function ThumbnailDetailsFromJSON(json: any): ThumbnailDetails {
    return ThumbnailDetailsFromJSONTyped(json, false);
}

export function ThumbnailDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThumbnailDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_default': !exists(json, 'default__') ? undefined : ThumbnailFromJSON(json['default__']),
        'high': !exists(json, 'high') ? undefined : ThumbnailFromJSON(json['high']),
        'maxres': !exists(json, 'maxres') ? undefined : ThumbnailFromJSON(json['maxres']),
        'medium': !exists(json, 'medium') ? undefined : ThumbnailFromJSON(json['medium']),
        'standard': !exists(json, 'standard') ? undefined : ThumbnailFromJSON(json['standard']),
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function ThumbnailDetailsToJSON(value?: ThumbnailDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'default__': ThumbnailToJSON(value._default),
        'high': ThumbnailToJSON(value.high),
        'maxres': ThumbnailToJSON(value.maxres),
        'medium': ThumbnailToJSON(value.medium),
        'standard': ThumbnailToJSON(value.standard),
        'eTag': value.eTag,
    };
}


