/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnparsedResourceName
 */
export interface UnparsedResourceName {
    /**
     * 
     * @type {boolean}
     * @memberof UnparsedResourceName
     */
    readonly isKnownPattern?: boolean;
}

export function UnparsedResourceNameFromJSON(json: any): UnparsedResourceName {
    return UnparsedResourceNameFromJSONTyped(json, false);
}

export function UnparsedResourceNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnparsedResourceName {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isKnownPattern': !exists(json, 'isKnownPattern') ? undefined : json['isKnownPattern'],
    };
}

export function UnparsedResourceNameToJSON(value?: UnparsedResourceName | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


