/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoPlayer
 */
export interface VideoPlayer {
    /**
     * 
     * @type {number}
     * @memberof VideoPlayer
     */
    embedHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoPlayer
     */
    embedHtml?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VideoPlayer
     */
    embedWidth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoPlayer
     */
    eTag?: string | null;
}

export function VideoPlayerFromJSON(json: any): VideoPlayer {
    return VideoPlayerFromJSONTyped(json, false);
}

export function VideoPlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPlayer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embedHeight': !exists(json, 'embedHeight') ? undefined : json['embedHeight'],
        'embedHtml': !exists(json, 'embedHtml') ? undefined : json['embedHtml'],
        'embedWidth': !exists(json, 'embedWidth') ? undefined : json['embedWidth'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function VideoPlayerToJSON(value?: VideoPlayer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'embedHeight': value.embedHeight,
        'embedHtml': value.embedHtml,
        'embedWidth': value.embedWidth,
        'eTag': value.eTag,
    };
}


