/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoLiveStreamingDetails
 */
export interface VideoLiveStreamingDetails {
    /**
     * 
     * @type {string}
     * @memberof VideoLiveStreamingDetails
     */
    activeLiveChatId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoLiveStreamingDetails
     */
    actualEndTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoLiveStreamingDetails
     */
    actualStartTime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VideoLiveStreamingDetails
     */
    concurrentViewers?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoLiveStreamingDetails
     */
    scheduledEndTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoLiveStreamingDetails
     */
    scheduledStartTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoLiveStreamingDetails
     */
    eTag?: string | null;
}

export function VideoLiveStreamingDetailsFromJSON(json: any): VideoLiveStreamingDetails {
    return VideoLiveStreamingDetailsFromJSONTyped(json, false);
}

export function VideoLiveStreamingDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoLiveStreamingDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activeLiveChatId': !exists(json, 'activeLiveChatId') ? undefined : json['activeLiveChatId'],
        'actualEndTime': !exists(json, 'actualEndTime') ? undefined : json['actualEndTime'],
        'actualStartTime': !exists(json, 'actualStartTime') ? undefined : json['actualStartTime'],
        'concurrentViewers': !exists(json, 'concurrentViewers') ? undefined : json['concurrentViewers'],
        'scheduledEndTime': !exists(json, 'scheduledEndTime') ? undefined : json['scheduledEndTime'],
        'scheduledStartTime': !exists(json, 'scheduledStartTime') ? undefined : json['scheduledStartTime'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function VideoLiveStreamingDetailsToJSON(value?: VideoLiveStreamingDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activeLiveChatId': value.activeLiveChatId,
        'actualEndTime': value.actualEndTime,
        'actualStartTime': value.actualStartTime,
        'concurrentViewers': value.concurrentViewers,
        'scheduledEndTime': value.scheduledEndTime,
        'scheduledStartTime': value.scheduledStartTime,
        'eTag': value.eTag,
    };
}


