/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccessPolicy,
    AccessPolicyFromJSON,
    AccessPolicyFromJSONTyped,
    AccessPolicyToJSON,
    ContentRating,
    ContentRatingFromJSON,
    ContentRatingFromJSONTyped,
    ContentRatingToJSON,
    VideoContentDetailsRegionRestriction,
    VideoContentDetailsRegionRestrictionFromJSON,
    VideoContentDetailsRegionRestrictionFromJSONTyped,
    VideoContentDetailsRegionRestrictionToJSON,
} from './';

/**
 * 
 * @export
 * @interface VideoContentDetails
 */
export interface VideoContentDetails {
    /**
     * 
     * @type {string}
     * @memberof VideoContentDetails
     */
    caption?: string | null;
    /**
     * 
     * @type {ContentRating}
     * @memberof VideoContentDetails
     */
    contentRating?: ContentRating;
    /**
     * 
     * @type {AccessPolicy}
     * @memberof VideoContentDetails
     */
    countryRestriction?: AccessPolicy;
    /**
     * 
     * @type {string}
     * @memberof VideoContentDetails
     */
    definition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoContentDetails
     */
    dimension?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoContentDetails
     */
    duration?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof VideoContentDetails
     */
    hasCustomThumbnail?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof VideoContentDetails
     */
    licensedContent?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof VideoContentDetails
     */
    projection?: string | null;
    /**
     * 
     * @type {VideoContentDetailsRegionRestriction}
     * @memberof VideoContentDetails
     */
    regionRestriction?: VideoContentDetailsRegionRestriction;
    /**
     * 
     * @type {string}
     * @memberof VideoContentDetails
     */
    eTag?: string | null;
}

export function VideoContentDetailsFromJSON(json: any): VideoContentDetails {
    return VideoContentDetailsFromJSONTyped(json, false);
}

export function VideoContentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoContentDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'caption': !exists(json, 'caption') ? undefined : json['caption'],
        'contentRating': !exists(json, 'contentRating') ? undefined : ContentRatingFromJSON(json['contentRating']),
        'countryRestriction': !exists(json, 'countryRestriction') ? undefined : AccessPolicyFromJSON(json['countryRestriction']),
        'definition': !exists(json, 'definition') ? undefined : json['definition'],
        'dimension': !exists(json, 'dimension') ? undefined : json['dimension'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'hasCustomThumbnail': !exists(json, 'hasCustomThumbnail') ? undefined : json['hasCustomThumbnail'],
        'licensedContent': !exists(json, 'licensedContent') ? undefined : json['licensedContent'],
        'projection': !exists(json, 'projection') ? undefined : json['projection'],
        'regionRestriction': !exists(json, 'regionRestriction') ? undefined : VideoContentDetailsRegionRestrictionFromJSON(json['regionRestriction']),
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function VideoContentDetailsToJSON(value?: VideoContentDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'caption': value.caption,
        'contentRating': ContentRatingToJSON(value.contentRating),
        'countryRestriction': AccessPolicyToJSON(value.countryRestriction),
        'definition': value.definition,
        'dimension': value.dimension,
        'duration': value.duration,
        'hasCustomThumbnail': value.hasCustomThumbnail,
        'licensedContent': value.licensedContent,
        'projection': value.projection,
        'regionRestriction': VideoContentDetailsRegionRestrictionToJSON(value.regionRestriction),
        'eTag': value.eTag,
    };
}


