/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoFileDetailsVideoStream
 */
export interface VideoFileDetailsVideoStream {
    /**
     * 
     * @type {number}
     * @memberof VideoFileDetailsVideoStream
     */
    aspectRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoFileDetailsVideoStream
     */
    bitrateBps?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoFileDetailsVideoStream
     */
    codec?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VideoFileDetailsVideoStream
     */
    frameRateFps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoFileDetailsVideoStream
     */
    heightPixels?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoFileDetailsVideoStream
     */
    rotation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoFileDetailsVideoStream
     */
    vendor?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VideoFileDetailsVideoStream
     */
    widthPixels?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoFileDetailsVideoStream
     */
    eTag?: string | null;
}

export function VideoFileDetailsVideoStreamFromJSON(json: any): VideoFileDetailsVideoStream {
    return VideoFileDetailsVideoStreamFromJSONTyped(json, false);
}

export function VideoFileDetailsVideoStreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoFileDetailsVideoStream {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aspectRatio': !exists(json, 'aspectRatio') ? undefined : json['aspectRatio'],
        'bitrateBps': !exists(json, 'bitrateBps') ? undefined : json['bitrateBps'],
        'codec': !exists(json, 'codec') ? undefined : json['codec'],
        'frameRateFps': !exists(json, 'frameRateFps') ? undefined : json['frameRateFps'],
        'heightPixels': !exists(json, 'heightPixels') ? undefined : json['heightPixels'],
        'rotation': !exists(json, 'rotation') ? undefined : json['rotation'],
        'vendor': !exists(json, 'vendor') ? undefined : json['vendor'],
        'widthPixels': !exists(json, 'widthPixels') ? undefined : json['widthPixels'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function VideoFileDetailsVideoStreamToJSON(value?: VideoFileDetailsVideoStream | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aspectRatio': value.aspectRatio,
        'bitrateBps': value.bitrateBps,
        'codec': value.codec,
        'frameRateFps': value.frameRateFps,
        'heightPixels': value.heightPixels,
        'rotation': value.rotation,
        'vendor': value.vendor,
        'widthPixels': value.widthPixels,
        'eTag': value.eTag,
    };
}


