/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoTopicDetails
 */
export interface VideoTopicDetails {
    /**
     * 
     * @type {Array<string>}
     * @memberof VideoTopicDetails
     */
    relevantTopicIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof VideoTopicDetails
     */
    topicCategories?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof VideoTopicDetails
     */
    topicIds?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof VideoTopicDetails
     */
    eTag?: string | null;
}

export function VideoTopicDetailsFromJSON(json: any): VideoTopicDetails {
    return VideoTopicDetailsFromJSONTyped(json, false);
}

export function VideoTopicDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoTopicDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'relevantTopicIds': !exists(json, 'relevantTopicIds') ? undefined : json['relevantTopicIds'],
        'topicCategories': !exists(json, 'topicCategories') ? undefined : json['topicCategories'],
        'topicIds': !exists(json, 'topicIds') ? undefined : json['topicIds'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function VideoTopicDetailsToJSON(value?: VideoTopicDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relevantTopicIds': value.relevantTopicIds,
        'topicCategories': value.topicCategories,
        'topicIds': value.topicIds,
        'eTag': value.eTag,
    };
}


