/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoStatistics
 */
export interface VideoStatistics {
    /**
     * 
     * @type {number}
     * @memberof VideoStatistics
     */
    commentCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoStatistics
     */
    dislikeCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoStatistics
     */
    favoriteCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoStatistics
     */
    likeCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoStatistics
     */
    viewCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoStatistics
     */
    eTag?: string | null;
}

export function VideoStatisticsFromJSON(json: any): VideoStatistics {
    return VideoStatisticsFromJSONTyped(json, false);
}

export function VideoStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoStatistics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentCount': !exists(json, 'commentCount') ? undefined : json['commentCount'],
        'dislikeCount': !exists(json, 'dislikeCount') ? undefined : json['dislikeCount'],
        'favoriteCount': !exists(json, 'favoriteCount') ? undefined : json['favoriteCount'],
        'likeCount': !exists(json, 'likeCount') ? undefined : json['likeCount'],
        'viewCount': !exists(json, 'viewCount') ? undefined : json['viewCount'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function VideoStatisticsToJSON(value?: VideoStatistics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commentCount': value.commentCount,
        'dislikeCount': value.dislikeCount,
        'favoriteCount': value.favoriteCount,
        'likeCount': value.likeCount,
        'viewCount': value.viewCount,
        'eTag': value.eTag,
    };
}


