/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoFileDetailsAudioStream
 */
export interface VideoFileDetailsAudioStream {
    /**
     * 
     * @type {number}
     * @memberof VideoFileDetailsAudioStream
     */
    bitrateBps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoFileDetailsAudioStream
     */
    channelCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoFileDetailsAudioStream
     */
    codec?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoFileDetailsAudioStream
     */
    vendor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoFileDetailsAudioStream
     */
    eTag?: string | null;
}

export function VideoFileDetailsAudioStreamFromJSON(json: any): VideoFileDetailsAudioStream {
    return VideoFileDetailsAudioStreamFromJSONTyped(json, false);
}

export function VideoFileDetailsAudioStreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoFileDetailsAudioStream {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bitrateBps': !exists(json, 'bitrateBps') ? undefined : json['bitrateBps'],
        'channelCount': !exists(json, 'channelCount') ? undefined : json['channelCount'],
        'codec': !exists(json, 'codec') ? undefined : json['codec'],
        'vendor': !exists(json, 'vendor') ? undefined : json['vendor'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function VideoFileDetailsAudioStreamToJSON(value?: VideoFileDetailsAudioStream | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bitrateBps': value.bitrateBps,
        'channelCount': value.channelCount,
        'codec': value.codec,
        'vendor': value.vendor,
        'eTag': value.eTag,
    };
}


