/* tslint:disable */
/* eslint-disable */
/**
 * AutoVideoMetaLocalize
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WatchSettings
 */
export interface WatchSettings {
    /**
     * 
     * @type {string}
     * @memberof WatchSettings
     */
    backgroundColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WatchSettings
     */
    featuredPlaylistId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WatchSettings
     */
    textColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WatchSettings
     */
    eTag?: string | null;
}

export function WatchSettingsFromJSON(json: any): WatchSettings {
    return WatchSettingsFromJSONTyped(json, false);
}

export function WatchSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'backgroundColor': !exists(json, 'backgroundColor') ? undefined : json['backgroundColor'],
        'featuredPlaylistId': !exists(json, 'featuredPlaylistId') ? undefined : json['featuredPlaylistId'],
        'textColor': !exists(json, 'textColor') ? undefined : json['textColor'],
        'eTag': !exists(json, 'eTag') ? undefined : json['eTag'],
    };
}

export function WatchSettingsToJSON(value?: WatchSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'backgroundColor': value.backgroundColor,
        'featuredPlaylistId': value.featuredPlaylistId,
        'textColor': value.textColor,
        'eTag': value.eTag,
    };
}


